// AUTO-GENERATED + curated. Single source of truth for every tweak in the app.
  // Source: client/src/store/use-optimization-store.ts DEFAULT_TWEAKS keys.
  // See .local/v2-audit-report.md for kept/fixed/merged/removed history.

  export type TweakSafety = "safe" | "aggressive" | "expert";
  export type TweakCategory =
    | "registry" | "network" | "fivem" | "nvidia" | "amd" | "intgpu"
    | "laptop" | "memory" | "fortnite" | "discord" | "debloat" | "wintitus"
    | "startup" | "processes" | "process-lasso" | "game-detection";

  export interface TweakMeta {
    id: string;
    category: TweakCategory;
    safety: TweakSafety;
    plainEnglish: string;       // ≤140 chars, human-friendly
    verifiedOn: { win10: boolean; win11: boolean };
  }

  export const TWEAK_REGISTRY: TweakMeta[] = [
    { id: "Win32PrioritySeparation", category: "registry", safety: "safe", plainEnglish: "Tunes CPU scheduling so your foreground game gets more priority over background apps.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableHungAppDetection", category: "registry", safety: "aggressive", plainEnglish: "Stops Windows from showing the 'not responding' dialog on busy apps.", verifiedOn: { win10: true, win11: true } },
  { id: "DisablePagefileEncryption", category: "registry", safety: "expert", plainEnglish: "Turns off encryption of the pagefile to remove disk write overhead.", verifiedOn: { win10: true, win11: true } },
  { id: "SetTimerResolution", category: "registry", safety: "safe", plainEnglish: "Sets a finer system timer so frame timing and input feel more responsive.", verifiedOn: { win10: true, win11: true } },
  { id: "SetResponsiveness", category: "registry", safety: "safe", plainEnglish: "Lets games claim more CPU time over Windows multimedia background tasks.", verifiedOn: { win10: true, win11: true } },
  { id: "EnableMSIMode", category: "registry", safety: "safe", plainEnglish: "Switches your GPU/NIC interrupts to MSI mode for lower input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "GameModeTweaks", category: "registry", safety: "safe", plainEnglish: "Turns on Windows Game Mode so games get CPU/GPU priority.", verifiedOn: { win10: true, win11: true } },
  { id: "NetworkThrottling", category: "network", safety: "safe", plainEnglish: "Removes the Windows cap on network packet throughput.", verifiedOn: { win10: true, win11: true } },
  { id: "OptimizeTCP", category: "network", safety: "safe", plainEnglish: "Applies low-latency TCP settings for online gaming.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableNagle", category: "network", safety: "safe", plainEnglish: "Disables packet batching so small game packets send instantly.", verifiedOn: { win10: true, win11: true } },
  { id: "InputLagTCP", category: "network", safety: "safe", plainEnglish: "Lowers TCP ack delay to reduce online input lag.", verifiedOn: { win10: true, win11: true } },
  { id: "EnableTCPAutoTuning", category: "network", safety: "safe", plainEnglish: "Lets Windows auto-size TCP windows for better throughput.", verifiedOn: { win10: true, win11: true } },
  { id: "DisablePowerThrottling", category: "registry", safety: "safe", plainEnglish: "Stops Windows from throttling background CPU work that your game depends on.", verifiedOn: { win10: true, win11: true } },
  { id: "SetDNSPriority", category: "network", safety: "safe", plainEnglish: "Raises DNS resolver priority so lookups don't stall your game.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableNDU", category: "network", safety: "safe", plainEnglish: "Disables Network Diagnostic Usage service to cut background polling.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableIPv6", category: "network", safety: "safe", plainEnglish: "Disables IPv6 to force IPv4-only routing, often more stable for gaming.", verifiedOn: { win10: true, win11: true } },
  { id: "DisablePrefetch", category: "registry", safety: "safe", plainEnglish: "Stops Windows from pre-loading apps you may not run.", verifiedOn: { win10: true, win11: true } },
  { id: "ClearPagefileOnShutdown", category: "registry", safety: "safe", plainEnglish: "Wipes the pagefile on shutdown for cleaner restarts.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableMemoryCompression", category: "registry", safety: "expert", plainEnglish: "Stops Windows from compressing RAM pages (frees CPU, costs more RAM).", verifiedOn: { win10: true, win11: true } },
  { id: "OptimizeRAMUsage", category: "registry", safety: "safe", plainEnglish: "Adjusts working-set sizing so foreground apps keep more RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableAnimations", category: "registry", safety: "safe", plainEnglish: "Turns off Windows animations to free GPU compositor work.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableTelemetry", category: "registry", safety: "aggressive", plainEnglish: "Blocks Microsoft telemetry traffic and services.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableXboxGameBar", category: "registry", safety: "safe", plainEnglish: "Disables the Xbox Game Bar overlay.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableGameDVR", category: "registry", safety: "safe", plainEnglish: "Stops background game DVR recording.", verifiedOn: { win10: true, win11: true } },
  { id: "SysVisualBestPerf", category: "registry", safety: "safe", plainEnglish: "Sets Windows visual effects to 'best performance'.", verifiedOn: { win10: true, win11: true } },
  { id: "SysHibernateOff", category: "registry", safety: "aggressive", plainEnglish: "Disables hibernate and removes hiberfil.sys to free disk space.", verifiedOn: { win10: true, win11: true } },
  { id: "SysHypervisorOff", category: "registry", safety: "expert", plainEnglish: "Disables the Windows hypervisor (also disables WSL/Hyper-V).", verifiedOn: { win10: true, win11: true } },
  { id: "EnableHAGS", category: "registry", safety: "safe", plainEnglish: "Enables Hardware-Accelerated GPU Scheduling (good for RTX/RX 6000+).", verifiedOn: { win10: true, win11: true } },
  { id: "DisablePointerPrecision", category: "registry", safety: "safe", plainEnglish: "Turns off mouse acceleration for raw input.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableFastStartup", category: "registry", safety: "safe", plainEnglish: "Disables Fast Startup so cold boots use a clean kernel state.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableWindowsError", category: "registry", safety: "aggressive", plainEnglish: "Stops Windows Error Reporting from uploading crash data.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableAutoUpdate", category: "registry", safety: "aggressive", plainEnglish: "Stops Windows from auto-installing updates in the background.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableDefender", category: "registry", safety: "expert", plainEnglish: "Disables Microsoft Defender real-time protection (use only with another AV).", verifiedOn: { win10: true, win11: true } },
  { id: "SetHighPerformancePlan", category: "registry", safety: "safe", plainEnglish: "Activates the High Performance power plan.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableUSBSuspend", category: "registry", safety: "safe", plainEnglish: "Stops USB ports from sleeping (fixes mouse/keyboard dropouts).", verifiedOn: { win10: true, win11: true } },
  { id: "DisableCoreParking", category: "registry", safety: "safe", plainEnglish: "Keeps all CPU cores active under load to prevent ramp-up latency.", verifiedOn: { win10: true, win11: true } },
  { id: "DisablePowerThrottlingAdv", category: "registry", safety: "safe", plainEnglish: "Aggressive variant of power throttling disable.", verifiedOn: { win10: true, win11: true } },
  { id: "DisableDynamicTick", category: "registry", safety: "safe", plainEnglish: "Disables the kernel dynamic tick for steadier timing.", verifiedOn: { win10: true, win11: true } },
  { id: "NetDNSCloudflare", category: "network", safety: "safe", plainEnglish: "Sets Cloudflare 1.1.1.1 as your DNS for fast lookups.", verifiedOn: { win10: true, win11: true } },
  { id: "NetDNSGoogle", category: "network", safety: "safe", plainEnglish: "Sets Google 8.8.8.8 as your DNS for fast lookups.", verifiedOn: { win10: true, win11: true } },
  { id: "NetDisableQoS", category: "network", safety: "safe", plainEnglish: "Disables QoS packet scheduler that reserves bandwidth.", verifiedOn: { win10: true, win11: true } },
  { id: "NetInterruptModeration", category: "network", safety: "safe", plainEnglish: "Disables NIC interrupt moderation to lower input lag.", verifiedOn: { win10: true, win11: true } },
  { id: "NetRSSQueues", category: "network", safety: "safe", plainEnglish: "Enables Receive Side Scaling across CPU cores.", verifiedOn: { win10: true, win11: true } },
  { id: "NetAdapterPowerSave", category: "network", safety: "safe", plainEnglish: "Disables network adapter power saving.", verifiedOn: { win10: true, win11: true } },
  { id: "NetTCPChimneyOffload", category: "network", safety: "safe", plainEnglish: "Disables TCP Chimney Offload to keep stack on CPU (more consistent).", verifiedOn: { win10: true, win11: true } },
  { id: "Win11DisableVBS", category: "registry", safety: "expert", plainEnglish: "Disables Virtualization-Based Security (big FPS win, lowers security).", verifiedOn: { win10: true, win11: true } },
  { id: "Win11DisableHVCI", category: "registry", safety: "expert", plainEnglish: "Disables Memory Integrity / HVCI (big FPS win, lowers security).", verifiedOn: { win10: true, win11: true } },
  { id: "Win11ParkingCoreOverride", category: "registry", safety: "aggressive", plainEnglish: "Overrides Win11 default core parking policy.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11ProcessorIdleMin", category: "registry", safety: "aggressive", plainEnglish: "Raises minimum CPU idle floor so cores stay alert.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcNUMAAware", category: "registry", safety: "safe", plainEnglish: "Hints scheduler to be NUMA-aware on multi-die CPUs (Threadripper/EPYC).", verifiedOn: { win10: true, win11: true } },
  { id: "ProcAffinityFPS", category: "registry", safety: "safe", plainEnglish: "Sets a default affinity mask that favors P-cores.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcMMCSSGaming", category: "registry", safety: "safe", plainEnglish: "Raises the Games MMCSS class to Guaranteed.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcGPUSchedulerHigh", category: "registry", safety: "safe", plainEnglish: "Raises GPU scheduler priority for games.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMCacheClear", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMHighPriority", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMDisablePhysX", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMExtendedMemory", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMNetworkBuffer", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMDisableVSync", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMStreamDistance", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMDisableFullscreen", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMDisableDWM", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMAffinityMask", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMIOPriority", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMDisableP2P", category: "fivem", safety: "expert", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMDNSOverride", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMQueueFix", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMWorkingSet", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMStreamPool", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMDisableNvidiaTelemetry", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMMenuFpsUncap", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMDisableMemCompression", category: "fivem", safety: "aggressive", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMDisableLSO", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMEnableRSS", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMReduceNPCDensity", category: "fivem", safety: "aggressive", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMReduceShadowQuality", category: "fivem", safety: "aggressive", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMCommandLineTweaks", category: "fivem", safety: "aggressive", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMFullPerfStack", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMGTAProcessPerfOptions", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMGameModeAdd", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMRenderingBoost", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMGPUPriorityStack", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveM1060VRAMFlag", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveM1060DisableHAGS", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveM1060AnselDisable", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveM5600CoreAffinity", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveM5600PowerPlan", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveM1650DisableHAGS", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveM1650VRAMBudget", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveM1650DisableAnsel", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveM1650LowLatencyMode", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveM3500CoreAffinity", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveM3500PerfPlan", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMCitizenDisableMedia", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMSteamChildOff", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMCommandlineMax", category: "fivem", safety: "aggressive", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMSteamOverlayOff", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMMMCSSAudio", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMDisableMPO", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMFixNvidiaOverlay", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "FiveMFixProductId", category: "fivem", safety: "safe", plainEnglish: "FiveM / GTA V tweak — improves performance, latency, or stability for FiveM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcessLassoProBalance", category: "process-lasso", safety: "safe", plainEnglish: "Process Lasso automation rule for CPU affinity/priority.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcessLassoSmartTrim", category: "process-lasso", safety: "safe", plainEnglish: "Process Lasso automation rule for CPU affinity/priority.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcessLassoRestrain", category: "process-lasso", safety: "aggressive", plainEnglish: "Process Lasso automation rule for CPU affinity/priority.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcessLassoAffinityGaming", category: "process-lasso", safety: "safe", plainEnglish: "Process Lasso automation rule for CPU affinity/priority.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcessLassoInstanceBalancer", category: "process-lasso", safety: "safe", plainEnglish: "Process Lasso automation rule for CPU affinity/priority.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcessTrimWorkingSet", category: "processes", safety: "safe", plainEnglish: "Sets ProcessTrimWorkingSet service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcessDisableWindowsErrorReporting", category: "processes", safety: "safe", plainEnglish: "Sets ProcessDisableWindowsErrorReporting service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcessAutoKillHung", category: "processes", safety: "aggressive", plainEnglish: "Sets ProcessAutoKillHung service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatCortana", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Cortana to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatOneDrive", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables OneDrive to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatXboxApp", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables XboxApp to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatXboxGameBar", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables XboxGameBar to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatXboxIdentity", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables XboxIdentity to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatBing", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Bing to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatWeather", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Weather to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatNews", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables News to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatMaps", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Maps to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatSolitaire", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Solitaire to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatMixedReality", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables MixedReality to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatSkype", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Skype to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatZune", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Zune to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatGrooveMusic", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables GrooveMusic to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatOfficeHub", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables OfficeHub to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatFeedback", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Feedback to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatGetHelp", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables GetHelp to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatMSPaint3D", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables MSPaint3D to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatWindowsCamera", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables WindowsCamera to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatYourPhone", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables YourPhone to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatClipchamp", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Clipchamp to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatPowerAutomate", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables PowerAutomate to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatQuickAssist", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables QuickAssist to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatTeamsConsumer", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables TeamsConsumer to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "DebloatAlarmsAndClock", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables AlarmsAndClock to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceDiagTrack", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables DiagTrack to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceWSearch", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables WSearch to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceSysMain", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables SysMain to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceRemoteReg", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables RemoteReg to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceWMPNetworkSvc", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables WMPNetworkSvc to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceFax", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Fax to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceRetailDemo", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables RetailDemo to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceTabletInput", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables TabletInput to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceMapsBroker", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables MapsBroker to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceWerSvc", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables WerSvc to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceDPS", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables DPS to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServicePrintSpooler", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables PrintSpooler to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceDusmSvc", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables DusmSvc to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceTrkWks", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables TrkWks to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceLltdsvc", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Lltdsvc to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceFDHost", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables FDHost to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceWbioSrvc", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables WbioSrvc to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServicePcaSvc", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables PcaSvc to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "ServiceAeLookupSvc", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables AeLookupSvc to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "PrivacyTelemetry", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Telemetry to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "PrivacyActivityHistory", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables ActivityHistory to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "PrivacyLocationTracking", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables LocationTracking to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "PrivacyAdvertisingID", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables AdvertisingID to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "PrivacyDiagFeedback", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables DiagFeedback to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11TeamsChat", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables TeamsChat to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11Widgets", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Widgets to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11Copilot", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Copilot to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11StartRecommended", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables StartRecommended to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11EdgeSidebar", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables EdgeSidebar to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11ChatIcon", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables ChatIcon to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11OneDriveBackup", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables OneDriveBackup to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11AdsInStart", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables AdsInStart to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11DeviceEncryption", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables DeviceEncryption to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11Snap", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables Snap to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11TPMAlert", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables TPMAlert to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11BingSearch", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables BingSearch to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11NotepadAI", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables NotepadAI to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "Win11AutoHDR", category: "debloat", safety: "aggressive", plainEnglish: "Removes / disables AutoHDR to free background resources.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdDisableULPS", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdDisableChill", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdDisablePowerEfficiency", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdDisableVSR", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdMaxClockState", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdDisableTelemetry", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdDisableCrashDefender", category: "amd", safety: "aggressive", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdOptimizeLatency", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdShaderCache", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdDisableFreeSyncCompetitive", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdDisableVariBright", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdForcePerformancePowerPlan", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdImageSharpening", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdAntiLag", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdDisableStartupApps", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdTDRTweak", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdSmartAccessMemory", category: "amd", safety: "aggressive", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdAntiLagPlus", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdFluidMotionFrames", category: "amd", safety: "aggressive", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdResizableBAR", category: "amd", safety: "aggressive", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdRadeonBoost", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdEnhancedSync", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaDisableTelemetry", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaMaxPerfMode", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaPreRenderedFrames", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaShaderCache", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaOptimizeLatency", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaDisableOverlay", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaLowLatency", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaThreadedOpt", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaForceVSyncOff", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaPowerMizer", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaAnisoFiltering", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaTripleBufferOff", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaReflexEnable", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaGSyncOptimize", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaOpenGLOpt", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaVRAMMax", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvShaderDiskCache", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvTextureFilterPerf", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvFXAADriverOff", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaCUDAPriority", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaShaderCacheUnlimited", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaFrameBufferOpt", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaDisableAnsel", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaDisableContainerLS", category: "nvidia", safety: "aggressive", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaDisableShadowPlay", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "MemFixedPagefile", category: "memory", safety: "safe", plainEnglish: "Sets a fixed pagefile size so Windows doesn't resize it mid-game.", verifiedOn: { win10: true, win11: true } },
  { id: "MemDisablePagefile", category: "memory", safety: "expert", plainEnglish: "Fully disables the pagefile (risky — drivers/crash dumps may break).", verifiedOn: { win10: true, win11: true } },
  { id: "MemClearPagefileShutdown", category: "memory", safety: "safe", plainEnglish: "Wipes the pagefile on shutdown.", verifiedOn: { win10: true, win11: true } },
  { id: "MemMovePagefileFast", category: "memory", safety: "safe", plainEnglish: "Moves the pagefile to your fastest detected drive.", verifiedOn: { win10: true, win11: true } },
  { id: "MemDisableCompression", category: "memory", safety: "expert", plainEnglish: "Disables memory compression (recommended only at 32GB+).", verifiedOn: { win10: true, win11: true } },
  { id: "MemDisableSuperfetch", category: "memory", safety: "aggressive", plainEnglish: "Disables SysMain/Superfetch background prefetching.", verifiedOn: { win10: true, win11: true } },
  { id: "MemTrimStandbyList", category: "memory", safety: "aggressive", plainEnglish: "Aggressively trims standby cache to free RAM for games.", verifiedOn: { win10: true, win11: true } },
  { id: "MemDisableKernelPaging", category: "memory", safety: "aggressive", plainEnglish: "Keeps the kernel locked in RAM so it never pages out.", verifiedOn: { win10: true, win11: true } },
  { id: "MemSystemCacheBoost", category: "memory", safety: "safe", plainEnglish: "Biases the file cache toward apps instead of system files.", verifiedOn: { win10: true, win11: true } },
  { id: "MemTrimOnMinimize", category: "memory", safety: "safe", plainEnglish: "Trims app working sets when minimized to free RAM for the game.", verifiedOn: { win10: true, win11: true } },
  { id: "MemLargePageSupport", category: "memory", safety: "safe", plainEnglish: "Enables 2MB large pages for DX12/Vulkan titles.", verifiedOn: { win10: true, win11: true } },
  { id: "MemSetWorkingSetSize", category: "memory", safety: "safe", plainEnglish: "Raises the per-process working set ceiling.", verifiedOn: { win10: true, win11: true } },
  { id: "MemDisableHeapTermination", category: "memory", safety: "expert", plainEnglish: "Stops Windows from killing apps on minor heap corruption.", verifiedOn: { win10: true, win11: true } },
  { id: "MemGPUOptimize", category: "memory", safety: "safe", plainEnglish: "Increases GPU virtual address space to reduce VRAM fragmentation.", verifiedOn: { win10: true, win11: true } },
  { id: "MemDisableGPUPagefile", category: "memory", safety: "aggressive", plainEnglish: "Prevents Windows from spilling VRAM into system RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "EnableLargeSystemCache", category: "memory", safety: "safe", plainEnglish: "Biases the system cache toward keeping more data in RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "MemGPUSchedulerTweak", category: "memory", safety: "safe", plainEnglish: "Tunes GPU memory scheduler for lower latency over throughput.", verifiedOn: { win10: true, win11: true } },
  { id: "game_valorant", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for valorant.", verifiedOn: { win10: true, win11: true } },
  { id: "game_cs2", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for cs2.", verifiedOn: { win10: true, win11: true } },
  { id: "game_apex", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for apex.", verifiedOn: { win10: true, win11: true } },
  { id: "game_warzone", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for warzone.", verifiedOn: { win10: true, win11: true } },
  { id: "game_lol", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for lol.", verifiedOn: { win10: true, win11: true } },
  { id: "game_overwatch", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for overwatch.", verifiedOn: { win10: true, win11: true } },
  { id: "game_siege", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for siege.", verifiedOn: { win10: true, win11: true } },
  { id: "game_rust", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for rust.", verifiedOn: { win10: true, win11: true } },
  { id: "game_minecraft", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for minecraft.", verifiedOn: { win10: true, win11: true } },
  { id: "game_roblox", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for roblox.", verifiedOn: { win10: true, win11: true } },
  { id: "game_tarkov", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for tarkov.", verifiedOn: { win10: true, win11: true } },
  { id: "game_pubg", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for pubg.", verifiedOn: { win10: true, win11: true } },
  { id: "game_dbd", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for dbd.", verifiedOn: { win10: true, win11: true } },
  { id: "game_dota2", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for dota2.", verifiedOn: { win10: true, win11: true } },
  { id: "game_warframe", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for warframe.", verifiedOn: { win10: true, win11: true } },
  { id: "game_forza", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for forza.", verifiedOn: { win10: true, win11: true } },
  { id: "game_readyornot", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for readyornot.", verifiedOn: { win10: true, win11: true } },
  { id: "game_phasmo", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for phasmo.", verifiedOn: { win10: true, win11: true } },
  { id: "game_battlefield", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for battlefield.", verifiedOn: { win10: true, win11: true } },
  { id: "game_gta5", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for gta5.", verifiedOn: { win10: true, win11: true } },
  { id: "game_fivem", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for fivem.", verifiedOn: { win10: true, win11: true } },
  { id: "game_rocketleague", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for rocketleague.", verifiedOn: { win10: true, win11: true } },
  { id: "game_arcraiders", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for arcraiders.", verifiedOn: { win10: true, win11: true } },
  { id: "game_marvelrivals", category: "game-detection", safety: "safe", plainEnglish: "Smart-detect helper for marvelrivals.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteHighPriority", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteUncapLobbyFPS", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteUncapGameFPS", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteDisableVSync", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteEngineStreaming", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteDisableMotionBlur", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteNetworkBuffer", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteLowShadows", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteDisableLumen", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteForceDirectX12", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteDisableRecording", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteAffinityPhysical", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteInputLatency", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteGameMode", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "FortniteDisableThrottling", category: "fortnite", safety: "safe", plainEnglish: "Fortnite-specific UE5/Lumen/engine tweak for better FPS or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusConsumerFeatures", category: "wintitus", safety: "aggressive", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusHibernation", category: "wintitus", safety: "aggressive", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusPosh7Telemetry", category: "wintitus", safety: "aggressive", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusWPBT", category: "wintitus", safety: "expert", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusDiskCleanup", category: "wintitus", safety: "aggressive", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusServicesManual", category: "wintitus", safety: "aggressive", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusAdobeBlock", category: "wintitus", safety: "aggressive", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusRazerBlock", category: "wintitus", safety: "aggressive", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusBgApps", category: "wintitus", safety: "aggressive", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusFullscreenOpt", category: "wintitus", safety: "safe", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusNotifTray", category: "wintitus", safety: "safe", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusStorageSense", category: "wintitus", safety: "aggressive", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusTeredo", category: "wintitus", safety: "aggressive", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusEdgeDebloat", category: "wintitus", safety: "safe", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusIPv4Prefer", category: "wintitus", safety: "safe", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusEdgeRemove", category: "wintitus", safety: "aggressive", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusXboxComponents", category: "wintitus", safety: "aggressive", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusClassicMenu", category: "wintitus", safety: "safe", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusDisplayPerf", category: "wintitus", safety: "safe", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusShowExtensions", category: "wintitus", safety: "safe", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "WinTitusShowHidden", category: "wintitus", safety: "safe", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "OOShutupPrivacy", category: "wintitus", safety: "aggressive", plainEnglish: "WinUtil / OO ShutUp privacy and debloat tweak.", verifiedOn: { win10: true, win11: true } },
  { id: "DiscordLowPriority", category: "discord", safety: "safe", plainEnglish: "Discord tweak that reduces its CPU, GPU, or RAM footprint while you game.", verifiedOn: { win10: true, win11: true } },
  { id: "DiscordDisableHWAccel", category: "discord", safety: "safe", plainEnglish: "Discord tweak that reduces its CPU, GPU, or RAM footprint while you game.", verifiedOn: { win10: true, win11: true } },
  { id: "DiscordClearCache", category: "discord", safety: "safe", plainEnglish: "Discord tweak that reduces its CPU, GPU, or RAM footprint while you game.", verifiedOn: { win10: true, win11: true } },
  { id: "DiscordDisableUpdateCheck", category: "discord", safety: "safe", plainEnglish: "Discord tweak that reduces its CPU, GPU, or RAM footprint while you game.", verifiedOn: { win10: true, win11: true } },
  { id: "DiscordReduceGPUPriority", category: "discord", safety: "safe", plainEnglish: "Discord tweak that reduces its CPU, GPU, or RAM footprint while you game.", verifiedOn: { win10: true, win11: true } },
  { id: "DiscordOptimizeCodec", category: "discord", safety: "safe", plainEnglish: "Discord tweak that reduces its CPU, GPU, or RAM footprint while you game.", verifiedOn: { win10: true, win11: true } },
  { id: "DiscordDisableCrashHandler", category: "discord", safety: "safe", plainEnglish: "Discord tweak that reduces its CPU, GPU, or RAM footprint while you game.", verifiedOn: { win10: true, win11: true } },
  { id: "DiscordDisableAnimations", category: "discord", safety: "safe", plainEnglish: "Discord tweak that reduces its CPU, GPU, or RAM footprint while you game.", verifiedOn: { win10: true, win11: true } },
  { id: "DiscordDisableOverlay", category: "discord", safety: "safe", plainEnglish: "Discord tweak that reduces its CPU, GPU, or RAM footprint while you game.", verifiedOn: { win10: true, win11: true } },
  { id: "DiscordDisableClips", category: "discord", safety: "safe", plainEnglish: "Discord tweak that reduces its CPU, GPU, or RAM footprint while you game.", verifiedOn: { win10: true, win11: true } },
  { id: "DiscordDisableVAD", category: "discord", safety: "safe", plainEnglish: "Discord tweak that reduces its CPU, GPU, or RAM footprint while you game.", verifiedOn: { win10: true, win11: true } },
  { id: "DiscordLowerVoiceQuality", category: "discord", safety: "safe", plainEnglish: "Discord tweak that reduces its CPU, GPU, or RAM footprint while you game.", verifiedOn: { win10: true, win11: true } },
  { id: "DiscordDisableStreaming", category: "discord", safety: "safe", plainEnglish: "Discord tweak that reduces its CPU, GPU, or RAM footprint while you game.", verifiedOn: { win10: true, win11: true } },
  { id: "su_discord", category: "startup", safety: "safe", plainEnglish: "Disables discord from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_spotify", category: "startup", safety: "safe", plainEnglish: "Disables spotify from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_steam", category: "startup", safety: "safe", plainEnglish: "Disables steam from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_onedrive", category: "startup", safety: "safe", plainEnglish: "Disables onedrive from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_teams", category: "startup", safety: "safe", plainEnglish: "Disables teams from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_skype", category: "startup", safety: "safe", plainEnglish: "Disables skype from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_zoom", category: "startup", safety: "safe", plainEnglish: "Disables zoom from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_rtss", category: "startup", safety: "safe", plainEnglish: "Disables rtss from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_msiab", category: "startup", safety: "safe", plainEnglish: "Disables msiab from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_nvidia", category: "startup", safety: "safe", plainEnglish: "Disables nvidia from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_ccleaner", category: "startup", safety: "safe", plainEnglish: "Disables ccleaner from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_realtek", category: "startup", safety: "safe", plainEnglish: "Disables realtek from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_logitech", category: "startup", safety: "safe", plainEnglish: "Disables logitech from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_corsair", category: "startup", safety: "safe", plainEnglish: "Disables corsair from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_amdradeon", category: "startup", safety: "safe", plainEnglish: "Disables amdradeon from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableULPS", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableDeepSleep", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableVariBright", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_ForcePerformancePower", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableTransparency", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableAnimations", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableHDR", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableNightLight", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableSysMain", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_GameModeOn", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_UltimatePerformancePlan", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_MaxProcessorState", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableFullscreenOpt", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableXboxGameBar", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_AmdAntiLag", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_SharedMemoryHint", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableDWMColorSpace", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_SetTimerResolution", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_CloseBrowserGPU", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableCoreParking", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_Intel_MaxFreq", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_Intel_DisableFreqScaling", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_Intel_TDR", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_Intel_PanelFitter", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_Intel_QSVOff", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableHAGSForIGpu", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_NetworkThrottling", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_DisableMPO", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_AmdTdrLevel", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_AmdDisableHDCP", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "IGpu_AmdVegaAudioOff", category: "intgpu", safety: "safe", plainEnglish: "Integrated GPU tweak (AMD Vega / Intel UHD) for smoother frames on iGPU systems.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_UltimatePerformance", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_DisableCoreParking", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_DisableThrottleStates", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_MaxProcessorStateAC", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_DisableTurboOnBattery", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_DisableAdaptiveBrightness", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_DisableHibernate", category: "laptop", safety: "expert", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_AMD_DisableULPS", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_AMD_DisableVariBright", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_AMD_DisableDeepSleep", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_AMD_DisableDynamicVoltage", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_AMD_ForcePerformance", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_NVIDIA_MaxPerformance", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_NVIDIA_DisableVsync", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_NVIDIA_LowLatency", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_NVIDIA_ThreadedOpt", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_NVIDIA_DisableMaxQThrottle", category: "laptop", safety: "aggressive", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_Intel_DisableTurboLimits", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_Intel_DisableSpeedShift", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_Intel_DisableECores", category: "laptop", safety: "aggressive", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_Net_DisableNagle", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_Net_DisableThrottle", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_Net_DisableAutoTuning", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_Net_OptimizeDNS", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_Net_DisableUSBSelSuspend", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_Net_WiFiPerfMode", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_TimerResolution", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_DisablePowerThrottling", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_DisableXboxGameBar", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_DisableFullscreenOpt", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_MMCSS_Games", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_DisableMPO", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_VisualPerformance", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_DisableHAGS", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_USBPowerSave", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "Lap_WifiPerfMode", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_DiagTrack", category: "processes", safety: "aggressive", plainEnglish: "Sets DiagTrack service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_WerSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets WerSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_DPS", category: "processes", safety: "aggressive", plainEnglish: "Sets DPS service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_DusmSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets DusmSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_DoSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets DoSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_XblAuth", category: "processes", safety: "aggressive", plainEnglish: "Sets XblAuth service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_XblGame", category: "processes", safety: "aggressive", plainEnglish: "Sets XblGame service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_XboxNet", category: "processes", safety: "aggressive", plainEnglish: "Sets XboxNet service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_XboxGip", category: "processes", safety: "aggressive", plainEnglish: "Sets XboxGip service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_SSDP", category: "processes", safety: "aggressive", plainEnglish: "Sets SSDP service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_FDServices", category: "processes", safety: "aggressive", plainEnglish: "Sets FDServices service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_Lltdsvc", category: "processes", safety: "aggressive", plainEnglish: "Sets Lltdsvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_SharedAccess", category: "processes", safety: "aggressive", plainEnglish: "Sets SharedAccess service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_WinRM", category: "processes", safety: "aggressive", plainEnglish: "Sets WinRM service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_WbioSrvc", category: "processes", safety: "aggressive", plainEnglish: "Sets WbioSrvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_TabletInput", category: "processes", safety: "aggressive", plainEnglish: "Sets TabletInput service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_BthServ", category: "processes", safety: "aggressive", plainEnglish: "Sets BthServ service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_Fax", category: "processes", safety: "aggressive", plainEnglish: "Sets Fax service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_MapsBroker", category: "processes", safety: "aggressive", plainEnglish: "Sets MapsBroker service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_lfsvc", category: "processes", safety: "aggressive", plainEnglish: "Sets lfsvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_PhoneSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets PhoneSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_RetailDemo", category: "processes", safety: "aggressive", plainEnglish: "Sets RetailDemo service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_WMPNet", category: "processes", safety: "aggressive", plainEnglish: "Sets WMPNet service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_TrkWks", category: "processes", safety: "aggressive", plainEnglish: "Sets TrkWks service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_W32Time", category: "processes", safety: "aggressive", plainEnglish: "Sets W32Time service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_BITS", category: "processes", safety: "aggressive", plainEnglish: "Sets BITS service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_WSearch", category: "processes", safety: "aggressive", plainEnglish: "Sets WSearch service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_SysMain", category: "processes", safety: "aggressive", plainEnglish: "Sets SysMain service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_RemoteReg", category: "processes", safety: "aggressive", plainEnglish: "Sets RemoteReg service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_ApplyAll", category: "processes", safety: "aggressive", plainEnglish: "Sets ApplyAll service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_OneSyncSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets OneSyncSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_CDPSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets CDPSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_WpnService", category: "processes", safety: "aggressive", plainEnglish: "Sets WpnService service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_cbdhsvc", category: "processes", safety: "aggressive", plainEnglish: "Sets cbdhsvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_dmwappushsvc", category: "processes", safety: "aggressive", plainEnglish: "Sets dmwappushsvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_PushToInstall", category: "processes", safety: "aggressive", plainEnglish: "Sets PushToInstall service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_AJRouter", category: "processes", safety: "aggressive", plainEnglish: "Sets AJRouter service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_SharedRealitySvc", category: "processes", safety: "aggressive", plainEnglish: "Sets SharedRealitySvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_icssvc", category: "processes", safety: "aggressive", plainEnglish: "Sets icssvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_WFDSConMgr", category: "processes", safety: "aggressive", plainEnglish: "Sets WFDSConMgr service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_p2pimsvc", category: "processes", safety: "aggressive", plainEnglish: "Sets p2pimsvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_EapHost", category: "processes", safety: "aggressive", plainEnglish: "Sets EapHost service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_seclogon", category: "processes", safety: "aggressive", plainEnglish: "Sets seclogon service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_SCardSvr", category: "processes", safety: "aggressive", plainEnglish: "Sets SCardSvr service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_AppReadiness", category: "processes", safety: "aggressive", plainEnglish: "Sets AppReadiness service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_PcaSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets PcaSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "ProcSvc_PrintNotify", category: "processes", safety: "aggressive", plainEnglish: "Sets PrintNotify service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaDisableHDMIAudio", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaRTXVideoOff", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "NvidiaGpuBgOptimize", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdCpuCoalescingOff", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdCpuPowerPinMax", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdCpuCStatePolicy", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdCpuCapabilities", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdCpuSchedulerHint", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdDisableHDMIAudio", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "AmdDisableReLive", category: "amd", safety: "aggressive", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
  { id: "RegistryNTFSOptimize", category: "network", safety: "aggressive", plainEnglish: "Disables NTFS last-access updates and 8.3 names to speed up disk I/O.", verifiedOn: { win10: true, win11: true } },
  { id: "RegistryIOPageLock", category: "network", safety: "expert", plainEnglish: "Increases the I/O page lock limit for high-throughput workloads.", verifiedOn: { win10: true, win11: true } },
  { id: "RegistryDPCLatency", category: "network", safety: "aggressive", plainEnglish: "Reduces DPC latency to smooth out frame-time spikes.", verifiedOn: { win10: true, win11: true } },
  { id: "RegistryLargePageHeap", category: "network", safety: "aggressive", plainEnglish: "Tells the heap to use large pages where supported.", verifiedOn: { win10: true, win11: true } },
  { id: "su_ea_app", category: "startup", safety: "safe", plainEnglish: "Disables ea_app from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_epic", category: "startup", safety: "safe", plainEnglish: "Disables epic from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_ubisoft", category: "startup", safety: "safe", plainEnglish: "Disables ubisoft from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_battlenet", category: "startup", safety: "safe", plainEnglish: "Disables battlenet from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_razer", category: "startup", safety: "safe", plainEnglish: "Disables razer from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_chrome", category: "startup", safety: "safe", plainEnglish: "Disables chrome from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_firefox", category: "startup", safety: "safe", plainEnglish: "Disables firefox from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_edge_startup", category: "startup", safety: "safe", plainEnglish: "Disables edge_startup from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  { id: "su_obs", category: "startup", safety: "safe", plainEnglish: "Disables obs from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
];

  export const TWEAK_BY_ID: Map<string, TweakMeta> = new Map(
    TWEAK_REGISTRY.map((t) => [t.id, t])
  );

  export function getTweakMeta(id: string): TweakMeta | undefined {
    return TWEAK_BY_ID.get(id);
  }

  export function tweaksByCategory(category: TweakCategory): TweakMeta[] {
    return TWEAK_REGISTRY.filter((t) => t.category === category);
  }

  export const TOTAL_TWEAK_COUNT = TWEAK_REGISTRY.length;

  export const SAFETY_LABEL: Record<TweakSafety, string> = {
    safe: "Safe",
    aggressive: "Aggressive",
    expert: "Expert",
  };

  export const SAFETY_DESCRIPTION: Record<TweakSafety, string> = {
    safe: "Reversible, broadly compatible. Safe defaults.",
    aggressive: "Bigger gains, but touches services/features some users want. Read the description.",
    expert: "Powerful but risky — can break boot, security, or driver stability if you don't understand it.",
  };
  