 true },
{ id: "Lap_WifiPerfMode", category: "laptop", safety: "safe", plainEnglish: "Laptop-specific tweak — thermal, power, network, or GPU optimization.", verifiedOn: { win10: true, win11: true }, title: "Disable Wi-Fi Power Save — Driver Registry (Deep)", description: "Writes PowerSaveMode=0 and PnPCapabilities=24 directly to the Wi-Fi adapter's driver class registry key. Unlike the netsh power management command, this registry path survives driver reinstalls and persists after power plan changes. Disabling Wi-Fi power save at the driver level removes the ~50-200ms latency spikes on budget Wi-Fi cards.", badge: "DEEP FIX", impact: "HIGH", recommended: true },
{ id: "ProcSvc_DiagTrack", category: "processes", safety: "aggressive", plainEnglish: "Sets DiagTrack service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "DiagTrack — Connected User Experiences & Telemetry", description: "Sends usage data and diagnostics to Microsoft continuously in the background. Setting to Manual stops it from auto-starting at boot.", badge: "RECOMMENDED", impact: "HIGH", recommended: true },
{ id: "ProcSvc_WerSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets WerSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "WerSvc — Windows Error Reporting", description: "Uploads crash dumps and error reports to Microsoft. Safe to set Manual — no impact on system stability.", badge: "RECOMMENDED", impact: "MED", recommended: true },
{ id: "ProcSvc_DPS", category: "processes", safety: "aggressive", plainEnglish: "Sets DPS service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "DPS — Diagnostics Policy Service", description: "Runs background hardware and network diagnostics. Not needed for gaming — consumes CPU cycles in the background.", impact: "MED", recommended: true },
{ id: "ProcSvc_DusmSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets DusmSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "DusmSvc — Data Usage Monitoring", description: "Tracks per-app network data usage for metered connections. Useless on unlimited home internet connections.", impact: "LOW", recommended: true },
{ id: "ProcSvc_DoSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets DoSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "DoSvc — Delivery Optimization", description: "Downloads Windows Updates and app packages using P2P. Uses background bandwidth. Manual stops it when not updating.", impact: "MED", recommended: true },
{ id: "ProcSvc_XblAuth", category: "processes", safety: "aggressive", plainEnglish: "Sets XblAuth service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "XblAuthManager — Xbox Live Auth Manager", description: "Handles Xbox Live authentication tokens. If you don't use Xbox Live / Game Pass, this can safely be set to Manual.", impact: "LOW", recommended: true },
{ id: "ProcSvc_XblGame", category: "processes", safety: "aggressive", plainEnglish: "Sets XblGame service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "XblGameSave — Xbox Live Game Save", description: "Syncs game saves to Xbox Live cloud. Safe to set Manual if you don't use Xbox cloud saves.", impact: "LOW", recommended: true },
{ id: "ProcSvc_XboxNet", category: "processes", safety: "aggressive", plainEnglish: "Sets XboxNet service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "XboxNetApiSvc — Xbox Live Networking Service", description: "Handles Xbox Live party chat and multiplayer matchmaking APIs. Set to Manual if not using Xbox apps.", impact: "LOW", recommended: true },
{ id: "ProcSvc_XboxGip", category: "processes", safety: "aggressive", plainEnglish: "Sets XboxGip service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "XboxGipSvc — Xbox Accessory Management", description: "Manages Xbox controller firmware and accessories. Set to Manual — starts on demand when controller is connected.", impact: "LOW" },
{ id: "ProcSvc_SSDP", category: "processes", safety: "aggressive", plainEnglish: "Sets SSDP service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "SSDPSRV + UPnP — Device Discovery", description: "SSDP Discovery and UPnP Device Host — used for auto-discovering network printers, TVs, and smart devices. Useless on pure gaming PCs.", impact: "LOW", recommended: true },
{ id: "ProcSvc_FDServices", category: "processes", safety: "aggressive", plainEnglish: "Sets FDServices service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "FDResPub + fdPHost — Function Discovery", description: "Publishes your PC to the local network for device discovery (printers, media servers). Safe to disable on standalone gaming PCs.", impact: "LOW", recommended: true },
{ id: "ProcSvc_Lltdsvc", category: "processes", safety: "aggressive", plainEnglish: "Sets Lltdsvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "lltdsvc — Link Layer Topology Discovery", description: "Used to build network topology maps (the network map in older Windows versions). Completely useless for gaming.", impact: "LOW", recommended: true },
{ id: "ProcSvc_SharedAccess", category: "processes", safety: "aggressive", plainEnglish: "Sets SharedAccess service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "SharedAccess — Internet Connection Sharing", description: "Enables sharing your internet connection with other devices. If you're not using your PC as a hotspot/router, this is useless.", impact: "LOW", recommended: true },
{ id: "ProcSvc_WinRM", category: "processes", safety: "aggressive", plainEnglish: "Sets WinRM service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "WinRM — Windows Remote Management", description: "Allows remote management of your PC over the network. Unnecessary and a mild security risk on home PCs.", impact: "LOW", recommended: true },
{ id: "ProcSvc_WbioSrvc", category: "processes", safety: "aggressive", plainEnglish: "Sets WbioSrvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "WbioSrvc — Windows Biometric Service", description: "Manages fingerprint readers and Windows Hello face recognition. Safe to set Manual if you use a PIN or password to log in.", impact: "LOW", recommended: true },
{ id: "ProcSvc_TabletInput", category: "processes", safety: "aggressive", plainEnglish: "Sets TabletInput service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "TabletInputService — Tablet Input Service", description: "Touch keyboard and handwriting recognition. Not needed on desktop gaming PCs without a touchscreen.", impact: "LOW", recommended: true },
{ id: "ProcSvc_BthServ", category: "processes", safety: "aggressive", plainEnglish: "Sets BthServ service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "bthserv — Bluetooth Support Service", description: "Bluetooth stack service. Set to Manual if you don't use Bluetooth devices — it will start on-demand when needed.", impact: "LOW", warning: "Only set Manual if you don't use a Bluetooth headset, controller, or mouse." },
{ id: "ProcSvc_Fax", category: "processes", safety: "aggressive", plainEnglish: "Sets Fax service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "Fax — Windows Fax Service", description: "Enables sending and receiving faxes. No gaming PC in 2025 needs this running.", badge: "RECOMMENDED", impact: "LOW", recommended: true },
{ id: "ProcSvc_MapsBroker", category: "processes", safety: "aggressive", plainEnglish: "Sets MapsBroker service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "MapsBroker — Downloaded Maps Manager", description: "Keeps offline maps updated. Useless if you don't use the Windows Maps app.", impact: "LOW", recommended: true },
{ id: "ProcSvc_lfsvc", category: "processes", safety: "aggressive", plainEnglish: "Sets lfsvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "lfsvc — Geolocation Service", description: "Provides location data to apps. Set Manual unless you use Windows apps that need your GPS location.", impact: "LOW", recommended: true },
{ id: "ProcSvc_PhoneSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets PhoneSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "PhoneSvc — Phone Service", description: "Manages VoIP and phone calls from Windows. Useless on standard gaming PCs.", impact: "LOW", recommended: true },
{ id: "ProcSvc_RetailDemo", category: "processes", safety: "aggressive", plainEnglish: "Sets RetailDemo service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "RetailDemo — Retail Demo Service", description: "Microsoft's store demo mode service. Absolutely no purpose on a personal PC.", badge: "RECOMMENDED", impact: "LOW", recommended: true },
{ id: "ProcSvc_WMPNet", category: "processes", safety: "aggressive", plainEnglish: "Sets WMPNet service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "WMPNetworkSvc — Windows Media Player Network", description: "Shares Windows Media Player libraries over the network. Useless if you don't use WMP for media sharing.", impact: "LOW", recommended: true },
{ id: "ProcSvc_TrkWks", category: "processes", safety: "aggressive", plainEnglish: "Sets TrkWks service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "TrkWks — Distributed Link Tracking Client", description: "Tracks NTFS shortcuts between drives on a network. Completely useless on standalone home PCs.", impact: "LOW", recommended: true },
{ id: "ProcSvc_W32Time", category: "processes", safety: "aggressive", plainEnglish: "Sets W32Time service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "W32Time — Windows Time", description: "Syncs your system clock with internet time servers. Safe to set Manual — clock still syncs on-demand when you open date/time settings.", impact: "LOW" },
{ id: "ProcSvc_BITS", category: "processes", safety: "aggressive", plainEnglish: "Sets BITS service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "BITS — Background Intelligent Transfer", description: "Used by Windows Update and other apps to download files in the background using spare bandwidth. Setting Manual stops it when idle.", impact: "MED", recommended: true },
{ id: "ProcSvc_WSearch", category: "processes", safety: "aggressive", plainEnglish: "Sets WSearch service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "WSearch — Windows Search (Indexing)", description: "Indexes your files for fast Start Menu search. Constant disk I/O. Set Manual if you use Everything or rarely use Windows search.", badge: "HIGH IMPACT", impact: "HIGH", recommended: true },
{ id: "ProcSvc_SysMain", category: "processes", safety: "aggressive", plainEnglish: "Sets SysMain service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "SysMain — Superfetch / Prefetch", description: "Pre-loads frequently used apps into RAM. Useful on HDDs, wasteful on NVMe/SSD systems. Set Manual if you have SSD + 16GB+ RAM.", badge: "16GB+ SSD", impact: "HIGH", recommended: true },
{ id: "ProcSvc_RemoteReg", category: "processes", safety: "aggressive", plainEnglish: "Sets RemoteReg service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "RemoteRegistry — Remote Registry", description: "Allows remote editing of this PC's registry over the network. Security risk — no home user needs this.", badge: "SECURITY", impact: "LOW", recommended: true },
{ id: "ProcSvc_ApplyAll", category: "processes", safety: "aggressive", plainEnglish: "Sets ApplyAll service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true } },
{ id: "ProcSvc_OneSyncSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets OneSyncSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "OneSyncSvc — Cloud Sync Platform", description: "Syncs your Microsoft account mail, contacts, calendar, and settings from the cloud at boot. Gaming PCs don't need this running constantly in the background.", badge: "RECOMMENDED", impact: "MED", recommended: true },
{ id: "ProcSvc_CDPSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets CDPSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "CDPSvc — Connected Devices Platform", description: "Pairs your PC with your phone and tablet for cross-device notifications. Spawns multiple worker processes. Safe to set Manual on standalone gaming PCs.", badge: "RECOMMENDED", impact: "MED", recommended: true },
{ id: "ProcSvc_WpnService", category: "processes", safety: "aggressive", plainEnglish: "Sets WpnService service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "WpnService — Windows Push Notifications", description: "Maintains push notification connections for UWP apps (Store apps). Spawns WpnUserService worker threads. Set Manual to stop constant cloud polling.", impact: "MED", recommended: true },
{ id: "ProcSvc_cbdhsvc", category: "processes", safety: "aggressive", plainEnglish: "Sets cbdhsvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "cbdhsvc — Clipboard User Service", description: "Powers Win+V clipboard history that syncs clipboard across devices. If you never use clipboard history, this runs for nothing.", impact: "LOW", recommended: true },
{ id: "ProcSvc_dmwappushsvc", category: "processes", safety: "aggressive", plainEnglish: "Sets dmwappushsvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "dmwappushsvc — WAP Push / MDM Router", description: "Routes WAP push messages for enterprise Mobile Device Management. Home gaming PCs have absolutely zero use for this service.", badge: "RECOMMENDED", impact: "LOW", recommended: true },
{ id: "ProcSvc_PushToInstall", category: "processes", safety: "aggressive", plainEnglish: "Sets PushToInstall service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "PushToInstall — Windows Store Remote Install", description: "Lets you push-install apps to your PC from the Microsoft Store app on your phone. Completely unnecessary daemon on gaming PCs.", impact: "LOW", recommended: true },
{ id: "ProcSvc_AJRouter", category: "processes", safety: "aggressive", plainEnglish: "Sets AJRouter service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "AJRouter — AllJoyn Router (IoT)", description: "Implements the AllJoyn smart home IoT protocol for connected devices. Gaming PCs have zero use for IoT routing — this is pure wasted overhead.", badge: "RECOMMENDED", impact: "LOW", recommended: true },
{ id: "ProcSvc_SharedRealitySvc", category: "processes", safety: "aggressive", plainEnglish: "Sets SharedRealitySvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "SharedRealitySvc — Mixed Reality Compositor", description: "Windows HoloLens and Mixed Reality runtime service. Runs spatial data processing in the background. Irrelevant on all standard gaming PCs.", badge: "RECOMMENDED", impact: "LOW", recommended: true },
{ id: "ProcSvc_icssvc", category: "processes", safety: "aggressive", plainEnglish: "Sets icssvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "icssvc — Windows Mobile Hotspot", description: "Manages internet sharing from your PC to other devices via Wi-Fi hotspot. If your PC isn't a hotspot, this process runs for nothing.", impact: "LOW", recommended: true },
{ id: "ProcSvc_WFDSConMgr", category: "processes", safety: "aggressive", plainEnglish: "Sets WFDSConMgr service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "WFDSConMgrSvc — Wi-Fi Direct Services", description: "Manages Miracast and Wi-Fi Direct wireless display connections. Useless on desktop gaming rigs not connected to wireless displays.", impact: "LOW", recommended: true },
{ id: "ProcSvc_p2pimsvc", category: "processes", safety: "aggressive", plainEnglish: "Sets p2pimsvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "p2pimsvc + PNRPsvc — Peer-to-Peer Networking", description: "Legacy Windows peer-to-peer discovery and name resolution protocols. Not used by any modern game or app. Both services stopped together.", badge: "RECOMMENDED", impact: "LOW", recommended: true },
{ id: "ProcSvc_EapHost", category: "processes", safety: "aggressive", plainEnglish: "Sets EapHost service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "EapHost — Extensible Authentication Protocol", description: "Enterprise WPA2-Enterprise and RADIUS 802.1X authentication. Home Wi-Fi uses WPA2-Personal — this service is never needed on home gaming PCs.", badge: "RECOMMENDED", impact: "LOW", recommended: true },
{ id: "ProcSvc_seclogon", category: "processes", safety: "aggressive", plainEnglish: "Sets seclogon service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "seclogon — Secondary Logon", description: "Allows running programs as a different user (Run As). Rarely used by home gamers. Starts on-demand if ever needed — safe to set Manual.", impact: "LOW", recommended: true },
{ id: "ProcSvc_SCardSvr", category: "processes", safety: "aggressive", plainEnglish: "Sets SCardSvr service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "SCardSvr + ScDeviceEnum — Smart Card Services", description: "Enterprise smart card reader hardware stack. No home gaming PC uses smart cards. Both services stopped and set to Manual together.", badge: "RECOMMENDED", impact: "LOW", recommended: true },
{ id: "ProcSvc_AppReadiness", category: "processes", safety: "aggressive", plainEnglish: "Sets AppReadiness service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "AppReadiness — App Readiness at Login", description: "Prepares UWP apps during user login on first boot. Wasteful on already-configured gaming PCs — adds latency to every login with no benefit.", impact: "LOW", recommended: true },
{ id: "ProcSvc_PcaSvc", category: "processes", safety: "aggressive", plainEnglish: "Sets PcaSvc service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "PcaSvc — Program Compatibility Assistant", description: "Monitors every app launch for compatibility issues with old Windows versions. Checks every crash, every new install. Pure CPU overhead on modern software.", badge: "RECOMMENDED", impact: "MED", recommended: true },
{ id: "ProcSvc_PrintNotify", category: "processes", safety: "aggressive", plainEnglish: "Sets PrintNotify service to manual to free CPU/RAM.", verifiedOn: { win10: true, win11: true }, title: "PrintNotify — Printer Extension Notifications", description: "Handles printer status pop-ups and extension UIs. Useless if you don't have an active printer attached. Starts on-demand if a printer is connected.", impact: "LOW", recommended: true },
{ id: "NvidiaDisableHDMIAudio", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
{ id: "NvidiaRTXVideoOff", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
{ id: "NvidiaGpuBgOptimize", category: "nvidia", safety: "safe", plainEnglish: "NVIDIA driver / registry tweak that improves frame pacing or input latency.", verifiedOn: { win10: true, win11: true } },
{ id: "AmdCpuCoalescingOff", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
{ id: "AmdCpuPowerPinMax", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
{ id: "AmdCpuCStatePolicy", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
{ id: "AmdCpuCapabilities", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
{ id: "AmdCpuSchedulerHint", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
{ id: "AmdDisableHDMIAudio", category: "amd", safety: "safe", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
{ id: "AmdDisableReLive", category: "amd", safety: "aggressive", plainEnglish: "AMD Radeon / Ryzen tweak that improves FPS, latency, or driver behavior.", verifiedOn: { win10: true, win11: true } },
{ id: "RegistryNTFSOptimize", category: "network", safety: "aggressive", plainEnglish: "Disables NTFS last-access updates and 8.3 names to speed up disk I/O.", verifiedOn: { win10: true, win11: true }, title: "NTFS: Disable Last Access Timestamp + 8.3 Filenames", description: "Disables NtfsDisableLastAccessUpdate (removes per-read disk write), NtfsDisable8dot3NameCreation (no legacy short filenames), and sets MftZoneReservation=2 (12.5% MFT reserve). Reduces disk I/O by ~5-10% during game asset streaming — especially noticeable in GTA V's streaming zones.", badge: "NTFS", impact: "MED" },
{ id: "RegistryIOPageLock", category: "network", safety: "expert", plainEnglish: "Increases the I/O page lock limit for high-throughput workloads.", verifiedOn: { win10: true, win11: true }, title: "Raise IOPageLockLimit for 16GB/32GB RAM Systems", description: "Sets IOPageLockLimit based on total RAM — 2GB for 32GB systems, 1GB for 16GB. Allows the kernel to lock more physical pages for DMA/I/O operations. Reduces streaming stutter and improves asset throughput in open-world games. Safe on systems with 16GB+.", badge: "MEMORY", impact: "MED", warning: "Only beneficial on systems with 16 GB+ RAM. On 8 GB or less, raising IOPageLockLimit can starve user-space processes of physical pages." },
{ id: "RegistryDPCLatency", category: "network", safety: "aggressive", plainEnglish: "Reduces DPC latency to smooth out frame-time spikes.", verifiedOn: { win10: true, win11: true }, title: "Reduce DPC Latency: AHCI Link Power Off + TSC Clock + No Dynamic Tick", description: "Disables AHCI link power management (eliminates DPC spikes from storage sleep states), switches boot clock to TSC (lower overhead than HPET), sets TSC sync=enhanced, and disables dynamic tick. Targets DPC latency spikes from 100-500µs down to under 50µs during GTA V streaming.", badge: "KERNEL", impact: "HIGH" },
{ id: "RegistryLargePageHeap", category: "network", safety: "aggressive", plainEnglish: "Tells the heap to use large pages where supported.", verifiedOn: { win10: true, win11: true }, title: "Set Accurate CPU Cache Hints + Disable Superfetch", description: "Writes SecondLevelDataCache=512KB and ThirdLevelDataCache=16384KB (matching Ryzen 5 3500 L2/L3). Enables Prefetcher mode 3 (App+Boot) and disables Superfetch. Windows uses cache size hints for heap allocation alignment — accurate values reduce cache line conflicts in memory-intensive game threads.", badge: "MEMORY", impact: "LOW" },
{ id: "su_ea_app", category: "startup", safety: "safe", plainEnglish: "Disables ea_app from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
{ id: "su_epic", category: "startup", safety: "safe", plainEnglish: "Disables epic from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
{ id: "su_ubisoft", category: "startup", safety: "safe", plainEnglish: "Disables ubisoft from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
{ id: "su_battlenet", category: "startup", safety: "safe", plainEnglish: "Disables battlenet from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
{ id: "su_razer", category: "startup", safety: "safe", plainEnglish: "Disables razer from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
{ id: "su_chrome", category: "startup", safety: "safe", plainEnglish: "Disables chrome from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
{ id: "su_firefox", category: "startup", safety: "safe", plainEnglish: "Disables firefox from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
{ id: "su_edge_startup", category: "startup", safety: "safe", plainEnglish: "Disables edge_startup from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
{ id: "su_obs", category: "startup", safety: "safe", plainEnglish: "Disables obs from auto-starting with Windows.", verifiedOn: { win10: true, win11: true } },
  // ===== V2 NEW (Task #38) =====
  { id: "NetMTUAutotune", category: "network", safety: "safe", plainEnglish: "Sets MTU to 1472 — the standard fragmentation-free size for competitive online games.", verifiedOn: { win10: true, win11: true }, title: "Set Wi-Fi MTU to 1472 (Fragmentation-Safe)", description: "Hard-sets the Wi-Fi interface MTU to 1472 bytes — the largest size guaranteed not to fragment over standard 1500-byte Ethernet routes. Eliminates fragmentation stalls in tick-rate-sensitive games. Run the Tauri build for true round-trip probing.", badge: "RECOMMENDED", impact: "MED", recommended: true, nativeAction: {"powershell":"netsh interface ipv4 set subinterface \"Wi-Fi\" mtu=1472 store=persistent","type":"powerCfg","params":{"kind":"mtu","target":1472}} },
  { id: "NetTCPAutotuneAggressive", category: "network", safety: "aggressive", plainEnglish: "Lets TCP windows grow faster on fast connections (best on fiber).", verifiedOn: { win10: true, win11: true }, title: "TCP Autotuning: Aggressive (experimental)", description: "Sets autotuninglevel=experimental + congestion=ctcp — bigger window growth on fast links. Can hurt slow/lossy connections, ideal for fiber.", badge: "MODERN", impact: "MED", warning: "On unstable or slow networks (DSL, weak Wi-Fi) this can make latency worse. Stick to the safer Optimize TCP/IP Stack tweak in that case.", nativeAction: {"powershell":"netsh int tcp set global autotuninglevel=experimental; netsh int tcp set global congestionprovider=ctcp","type":"powerCfg","params":{"kind":"tcpAutotune","level":"experimental"}} },
  { id: "NetRSSTuning", category: "network", safety: "safe", plainEnglish: "Pins network-card receive work to your fastest CPU core complex.", verifiedOn: { win10: true, win11: true }, title: "NDIS Receive-Side Scaling Tuning", description: "Caps RSS queues to 4 and pins them to the first physical CCX/core complex — reduces inter-core packet handoff latency on Ryzen/Intel hybrid CPUs.", impact: "MED", nativeAction: {"powershell":"Set-NetAdapterRss -Name * -NumberOfReceiveQueues 4 -BaseProcessorNumber 0 -MaxProcessors 4","type":"powerCfg","params":{"kind":"rss","numQueues":4}} },
  { id: "NetDNSQuad9", category: "network", safety: "safe", plainEnglish: "Switches DNS to Quad9 (9.9.9.9) — fast and blocks malicious domains.", verifiedOn: { win10: true, win11: true }, title: "DNS → Quad9 (9.9.9.9)", description: "Switches DNS to Quad9 — fast, blocks known-malicious domains. Alternative to Cloudflare/Google with extra security filtering.", badge: "MODERN", impact: "LOW", nativeAction: {"powershell":"Set-DnsClientServerAddress -InterfaceAlias \"Wi-Fi\" -ServerAddresses (\"9.9.9.9\",\"149.112.112.112\")","type":"powerCfg","params":{"kind":"dns","primary":"9.9.9.9","secondary":"149.112.112.112"}} },
  { id: "NetDisableLargeSendOffload", category: "network", safety: "safe", plainEnglish: "Disables NIC packet batching that adds latency in online games.", verifiedOn: { win10: true, win11: true }, title: "Disable Large Send Offload (LSO v1/v2)", description: "Turns LSO off on the NIC — known to add per-packet latency spikes on many Realtek + Killer NICs in online games. Keep off for competitive play.", impact: "MED", nativeAction: {"powershell":"Disable-NetAdapterLso -Name *","type":"powerCfg","params":{"kind":"lso","enabled":false}} },
  { id: "SecDetectVBSStatus", category: "registry", safety: "safe", plainEnglish: "Checks whether Virtualization-Based Security is currently costing you FPS.", verifiedOn: { win10: true, win11: true }, title: "Detect VBS / HVCI Status (read-only)", description: "Runs Get-CimInstance Win32_DeviceGuard and reports VBS + HVCI + Credential Guard status. Read-only — does not change anything.", badge: "DIAGNOSTIC", impact: "LOW", nativeAction: {"powershell":"Get-CimInstance -ClassName Win32_DeviceGuard -Namespace root\\Microsoft\\Windows\\DeviceGuard","type":"wmi","params":{"kind":"deviceGuardStatus"}} },
  { id: "SecDisableMemoryIntegrity", category: "registry", safety: "expert", plainEnglish: "Turns off HVCI for 4–12% more game FPS — lowers kernel-level malware defence.", verifiedOn: { win10: true, win11: true }, title: "Disable HVCI / Memory Integrity (FPS gain, security loss)", description: "Disables Hypervisor-Enforced Code Integrity. Frees 4–12% CPU in DX12/Vulkan games and removes a hypervisor frame-time spike, but lowers kernel-level malware protection. Requires reboot.", impact: "HIGH", warning: "Lowers security against kernel-level rootkits. Only disable if you understand the tradeoff and trust every app you run. Some anti-cheats (Vanguard) now REQUIRE Memory Integrity — disabling will block you from playing those games.", incompatibleWith: ["Vanguard"], nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard\\Scenarios\\HypervisorEnforcedCodeIntegrity' -Name 'Enabled' -Value 0 -Type DWord","type":"registry","params":{"hive":"HKLM","path":"SYSTEM\\CurrentControlSet\\Control\\DeviceGuard\\Scenarios\\HypervisorEnforcedCodeIntegrity","name":"Enabled","value":0,"type":"REG_DWORD"}} },
  { id: "SecDisableCredentialGuard", category: "registry", safety: "expert", plainEnglish: "Turns off Credential Guard (safe on home PCs, not on work laptops).", verifiedOn: { win10: true, win11: true }, incompatibleWith: ["Vanguard"], title: "Disable Credential Guard", description: "Disables LSA Credential Guard — frees a small amount of memory and reduces auth-related context switches. Safe on personal gaming PCs that aren't joined to a corporate domain.", impact: "LOW", warning: "DO NOT enable this on a work/domain-joined laptop — it removes IT-required credential protection.", nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name 'LsaCfgFlags' -Value 0 -Type DWord","type":"registry","params":{"hive":"HKLM","path":"SYSTEM\\CurrentControlSet\\Control\\Lsa","name":"LsaCfgFlags","value":0,"type":"REG_DWORD"}} },
  { id: "SecDisableMitigationsForGames", category: "registry", safety: "aggressive", plainEnglish: "Removes Windows exploit mitigations from a few game exes for cleaner frame pacing.", verifiedOn: { win10: true, win11: true }, title: "Disable Exploit Mitigations for Game Executables", description: "Adds MitigationOptions=0x222 entries under IFEO for common game exes (fortnite, cod, valorant, etc.) — removes CFG/ASLR/SEHOP overhead per-process. Other apps stay protected.", badge: "ADVANCED", impact: "MED", warning: "Reduces exploit protection on the affected game executables only — other apps stay protected. Don't enable for browsers or shell.", nativeAction: {"powershell":"# Loops over a list of game exe names and sets MitigationOptions=0x222 under HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\<exe>","type":"registry","params":{"kind":"mitigationOptionsBulk","value":"0x222"}} },
  { id: "ACDetectVanguard", category: "registry", safety: "safe", plainEnglish: "Detects Vanguard so the app can grey out tweaks Vanguard would ban you for.", verifiedOn: { win10: true, win11: true }, title: "Detect Riot Vanguard (Valorant / League)", description: "Checks for the Vanguard kernel driver (vgk.sys) and Vanguard service. Many aggressive tweaks (VBS off, HVCI off, kernel debugger on) are blocked by Vanguard — this flag tells Opti Gods which tweaks to grey out.", badge: "DIAGNOSTIC", impact: "LOW", nativeAction: {"powershell":"Get-Service -Name 'vgc','vgk' -ErrorAction SilentlyContinue | Select-Object Name,Status","type":"wmi","params":{"kind":"serviceDetect","names":["vgc","vgk"]}} },
  { id: "ACDetectEAC", category: "registry", safety: "safe", plainEnglish: "Detects Easy Anti-Cheat so risky tweaks are flagged.", verifiedOn: { win10: true, win11: true }, title: "Detect Easy Anti-Cheat (Fortnite / Apex / Rust)", description: "Looks for the EasyAntiCheat service + EasyAntiCheat_EOS.sys. When detected, Opti Gods avoids tweaks EAC interprets as unauthorized memory manipulation.", badge: "DIAGNOSTIC", impact: "LOW", nativeAction: {"powershell":"Get-Service -Name 'EasyAntiCheat','EasyAntiCheat_EOS' -ErrorAction SilentlyContinue | Select-Object Name,Status","type":"wmi","params":{"kind":"serviceDetect","names":["EasyAntiCheat","EasyAntiCheat_EOS"]}} },
  { id: "ACDetectBattlEyeFACEIT", category: "registry", safety: "safe", plainEnglish: "Combined BattlEye + FACEIT detector — one toggle flags both ACs.", verifiedOn: { win10: true, win11: true }, title: "Detect BattlEye + FACEIT (Combined)", description: "Single combined diagnostic: enabling this toggle marks BOTH BattlEye and FACEIT as installed. Both detect kernel-level tweaks, so they're grouped together until per-AC behavior diverges. Native script checks the BEService and FACEIT kernel drivers.", badge: "DIAGNOSTIC", impact: "LOW", nativeAction: {"powershell":"Get-Service -Name 'BEService','FACEIT' -ErrorAction SilentlyContinue | Select-Object Name,Status","type":"wmi","params":{"kind":"serviceDetect","names":["BEService","FACEIT"]}} },
  { id: "InputUSBPollingCheck", category: "registry", safety: "safe", plainEnglish: "Checks every USB HID device runs at 1000Hz polling for lowest input lag.", verifiedOn: { win10: true, win11: true }, title: "USB Polling Rate Check (1000Hz baseline)", description: "Reads the IdleEnable + EnhancedPowerManagementEnabled flags for every USB HID device and reports any that are below 1000Hz polling. Pairs with the USB Selective Suspend disable tweak.", badge: "DIAGNOSTIC", impact: "LOW", nativeAction: {"powershell":"Get-PnpDevice -Class HIDClass | ForEach-Object { Get-PnpDeviceProperty -InstanceId $_.InstanceId -KeyName 'DEVPKEY_Device_PowerData' }","type":"wmi","params":{"kind":"usbPollingScan"}} },
  { id: "InputRawAccelBanner", category: "registry", safety: "safe", plainEnglish: "Recommends RawAccel for consistent mouse aim — does not install anything.", verifiedOn: { win10: true, win11: true }, title: "RawAccel Recommend Banner", description: "Shows a one-time banner in the dashboard pointing users to RawAccel (open-source mouse accel) instead of Windows' Enhance Pointer Precision. Purely informational — does not install anything.", badge: "DIAGNOSTIC", impact: "LOW", nativeAction: {"powershell":"# No-op — UI banner only.","type":"tool","params":{"kind":"uiBanner","topic":"rawaccel"}} },
  { id: "InputMousePollHzVerify", category: "registry", safety: "safe", plainEnglish: "Measures your mouse's real polling rate (Hz) over 5 seconds.", verifiedOn: { win10: true, win11: true }, title: "Mouse Polling Rate Verifier", description: "Runs a short hardware-timing measurement (DirectInput timestamps over 5 seconds) and reports your actual measured mouse polling rate (e.g. 'measured 982Hz on Logitech G Pro X Superlight').", badge: "DIAGNOSTIC", impact: "LOW", nativeAction: {"powershell":"# UI-only on the web flow. The Tauri build will run a native DirectInput timer.","type":"tool","params":{"kind":"mousePollMeasure","durationSec":5}} },
  { id: "RTX50DLSS4FrameGen", category: "nvidia", safety: "safe", plainEnglish: "Turns on DLSS 4 multi-frame-gen for RTX 50 cards globally.", verifiedOn: { win10: true, win11: true }, title: "RTX 50: DLSS 4 Multi-Frame-Gen Defaults", description: "Sets NGXFrameGenerationMode=Multi and DLSSPresetJ in the NVIDIA driver registry — opts you into the new RTX 50 DLSS 4 frame-gen path globally. Requires R570+ driver.", badge: "MODERN", impact: "HIGH", recommended: true, nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\NVIDIA Corporation\\Global\\NGXCore' -Name 'FrameGenerationMode' -Value 'Multi' -Type String","type":"registry","params":{"hive":"HKLM","path":"SOFTWARE\\NVIDIA Corporation\\Global\\NGXCore","name":"FrameGenerationMode","value":"Multi"}} },
  { id: "RTX50Reflex2", category: "nvidia", safety: "safe", plainEnglish: "Enables NVIDIA Reflex 2 Frame Warp for ~30% lower input latency.", verifiedOn: { win10: true, win11: true }, title: "RTX 50: Reflex 2 (Frame Warp)", description: "Enables Reflex 2 Frame Warp globally via NVIDIA Profile Inspector key 0x10835000. Cuts input latency a further 20–40% over Reflex 1 on supported games.", badge: "MODERN", impact: "HIGH", recommended: true, nativeAction: {"powershell":"# Set via NVIDIA Profile Inspector key 0x10835000 = 0x00000001 (Reflex 2 ON)","type":"registry","params":{"hive":"NVPI","key":"0x10835000","value":1}} },
  { id: "RTX50PowerModeLock", category: "nvidia", safety: "safe", plainEnglish: "Locks your RTX 50 card to Max Performance — no idle down-clock.", verifiedOn: { win10: true, win11: true }, title: "RTX 50: Lock to Maximum Performance Power Mode", description: "Forces RmPowerMizerMode=1 + PowerMizerLevelAC=1 in the Blackwell driver registry — keeps the GPU at P0 instead of letting it down-clock between frames.", badge: "MODERN", impact: "HIGH", recommended: true, nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\nvlddmkm\\Parameters' -Name 'RmPowerMizerMode' -Value 1 -Type DWord","type":"registry","params":{"hive":"HKLM","path":"SYSTEM\\CurrentControlSet\\Services\\nvlddmkm\\Parameters","name":"RmPowerMizerMode","value":1,"type":"REG_DWORD"}} },
  { id: "RTX50ShaderCacheBump", category: "nvidia", safety: "safe", plainEnglish: "Raises the shader cache to 100GB so UE5 games stop recompiling shaders.", verifiedOn: { win10: true, win11: true }, title: "RTX 50: Shader Cache → 100GB", description: "Bumps DXShaderCacheSize to 100GB to match Blackwell's larger working set. Stops shader cache evictions in UE5/Nanite + Lumen games on RTX 50.", badge: "MODERN", impact: "MED", nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\NVIDIA Corporation\\Global\\NVTweak' -Name 'DXShaderCacheSize' -Value 107374182400 -Type QWord","type":"registry","params":{"hive":"HKLM","path":"SOFTWARE\\NVIDIA Corporation\\Global\\NVTweak","name":"DXShaderCacheSize","value":107374182400,"type":"REG_QWORD"}} },
  { id: "RTX50BlackwellDriverOpt", category: "nvidia", safety: "safe", plainEnglish: "Applies Blackwell-tuned driver defaults for cleaner frame pacing on RTX 50.", verifiedOn: { win10: true, win11: true }, title: "RTX 50: Blackwell-Specific Driver Profile", description: "Applies Blackwell-tuned driver defaults: PreemptionPolicy=Pixel, IGFX async compute on, MMIO write-combining mode on the Blackwell display engine.", badge: "MODERN", impact: "MED", nativeAction: {"powershell":"# Bulk driver profile via nvidia-smi + registry — see script template","type":"registry","params":{"kind":"blackwellProfileBulk"}} },
  { id: "RTX50ComputeSm120", category: "nvidia", safety: "aggressive", plainEnglish: "Tells CUDA + AI workloads to use the new sm_120 RTX 50 cores.", verifiedOn: { win10: true, win11: true }, title: "RTX 50: Prefer SM_120 Compute (CUDA + AI)", description: "Sets compute capability preference to sm_120 — gives RTX 50 cards the new tensor + RT cores in CUDA frame generation workloads.", badge: "MODERN", impact: "MED", nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\NVIDIA Corporation\\Global\\NVTweak' -Name 'PreferredComputeCapability' -Value 'sm_120' -Type String","type":"registry","params":{"hive":"HKLM","path":"SOFTWARE\\NVIDIA Corporation\\Global\\NVTweak","name":"PreferredComputeCapability","value":"sm_120"}} },
  { id: "RTX50NVCPSettings", category: "nvidia", safety: "safe", plainEnglish: "Applies the RTX 50 'performance defaults' to NVIDIA Control Panel globally.", verifiedOn: { win10: true, win11: true }, title: "RTX 50: NVCP Global Defaults (Performance)", description: "Applies the RTX 50 NVIDIA Control Panel performance defaults: Threaded Optimization=ON, Texture Filtering=High Performance, Power Management=Max Performance, Low-Latency Mode=Ultra, VRR=On.", badge: "MODERN", impact: "MED", recommended: true, nativeAction: {"powershell":"# Applies via NVIDIA Profile Inspector base profile keys","type":"registry","params":{"kind":"nvcpBulk","profile":"rtx50-perf"}} },
  { id: "RTX50NvidiaAppTelemetryOff", category: "nvidia", safety: "aggressive", plainEnglish: "Turns off telemetry from the new NVIDIA App (2025+ GeForce replacement).", verifiedOn: { win10: true, win11: true }, title: "RTX 50: NVIDIA App Telemetry OFF", description: "Disables the new NVIDIA App (GeForce Experience replacement) telemetry — stops the 2025+ NVIDIA App from background reporting + automatic driver-check pings.", badge: "MODERN", impact: "LOW", nativeAction: {"powershell":"Set-ItemProperty -Path 'HKCU:\\Software\\NVIDIA Corporation\\NVIDIA App\\Telemetry' -Name 'Enabled' -Value 0 -Type DWord","type":"registry","params":{"hive":"HKCU","path":"Software\\NVIDIA Corporation\\NVIDIA App\\Telemetry","name":"Enabled","value":0,"type":"REG_DWORD"}} },
  { id: "RX9000RDNA4AFMF2", category: "amd", safety: "safe", plainEnglish: "Enables AMD Fluid Motion Frames 2 on RX 9000 cards.", verifiedOn: { win10: true, win11: true }, title: "RX 9000: RDNA 4 AFMF 2 Defaults", description: "Enables AMD Fluid Motion Frames 2 on RDNA 4 cards globally — frame-gen for unsupported games. Requires Adrenalin 25.1+.", badge: "MODERN", impact: "HIGH", recommended: true, nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\AMD\\CN' -Name 'AFMF_Enable' -Value 2 -Type DWord","type":"registry","params":{"hive":"HKLM","path":"SOFTWARE\\AMD\\CN","name":"AFMF_Enable","value":2,"type":"REG_DWORD"}} },
  { id: "RX9000HyprRX", category: "amd", safety: "safe", plainEnglish: "Turns on AMD Hypr-RX (Anti-Lag + RSR + Boost + AFMF) globally.", verifiedOn: { win10: true, win11: true }, title: "RX 9000: Hypr-RX One-Click Defaults", description: "Enables AMD Hypr-RX (Anti-Lag + RSR + Boost + AFMF 2) globally — AMD's '1-click performance' bundle. Adrenalin 25.1+.", badge: "MODERN", impact: "HIGH", recommended: true, nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\AMD\\CN' -Name 'HyprRX_Enable' -Value 1 -Type DWord","type":"registry","params":{"hive":"HKLM","path":"SOFTWARE\\AMD\\CN","name":"HyprRX_Enable","value":1,"type":"REG_DWORD"}} },
  { id: "RX9000AntiLag2NextGen", category: "amd", safety: "safe", plainEnglish: "Enables Anti-Lag 2 NextGen (AMD's Reflex 2 equivalent).", verifiedOn: { win10: true, win11: true }, title: "RX 9000: Anti-Lag 2 NextGen", description: "Anti-Lag 2 NextGen — driver-level input latency reducer that ships with RDNA 4. Equivalent to NVIDIA Reflex 2.", badge: "MODERN", impact: "HIGH", recommended: true, nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\AMD\\CN' -Name 'AntiLag2_NextGen' -Value 1 -Type DWord","type":"registry","params":{"hive":"HKLM","path":"SOFTWARE\\AMD\\CN","name":"AntiLag2_NextGen","value":1,"type":"REG_DWORD"}} },
  { id: "RX9000PowerSlider", category: "amd", safety: "safe", plainEnglish: "Gives your RX 9000 card +15% power budget for sustained boost clocks.", verifiedOn: { win10: true, win11: true }, title: "RX 9000: Max Power Slider (+15%)", description: "Sets PowerLimit_Pct=15 in the Adrenalin tuning profile — gives the GPU 15% extra power headroom for sustained boost in heavy games.", badge: "MODERN", impact: "MED", nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\AMD\\CN\\OverDrive' -Name 'PowerLimit_Pct' -Value 15 -Type DWord","type":"registry","params":{"hive":"HKLM","path":"SOFTWARE\\AMD\\CN\\OverDrive","name":"PowerLimit_Pct","value":15,"type":"REG_DWORD"}} },
  { id: "RX9000Adrenalin2025TelemetryOff", category: "amd", safety: "aggressive", plainEnglish: "Disables telemetry in the 2025 build of AMD Adrenalin.", verifiedOn: { win10: true, win11: true }, title: "RX 9000: Adrenalin 2025 Telemetry OFF", description: "Disables the new (2025 build) Adrenalin telemetry endpoints, AMD Software Reporting Tool, and cloud profile sync.", badge: "MODERN", impact: "LOW", nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\AMD\\CN\\Telemetry' -Name 'Enabled' -Value 0 -Type DWord","type":"registry","params":{"hive":"HKLM","path":"SOFTWARE\\AMD\\CN\\Telemetry","name":"Enabled","value":0,"type":"REG_DWORD"}} },
  { id: "RX9000SAMVerify", category: "amd", safety: "safe", plainEnglish: "Reports whether Smart Access Memory (Resizable BAR) is actually active.", verifiedOn: { win10: true, win11: true }, title: "RX 9000: Verify Smart Access Memory Active", description: "Checks BAR1 size + UEFI Resizable BAR + AMD SAM driver state. Reports active/inactive status. Read-only diagnostic.", badge: "DIAGNOSTIC", impact: "LOW", nativeAction: {"powershell":"Get-WmiObject Win32_VideoController | Select-Object Name,AdapterRAM; (Get-CimInstance Win32_PnPSignedDriver | ? { $_.DeviceName -match 'AMD' })","type":"wmi","params":{"kind":"samStatus"}} },
  { id: "Zen5CurveOptimizer", category: "registry", safety: "safe", plainEnglish: "Shows recommended Curve Optimizer offsets for your Zen 5 9000-series CPU.", verifiedOn: { win10: true, win11: true }, title: "Zen 5: Curve Optimizer Recommend Banner", description: "Detects Zen 5 (9000-series Ryzen) and shows the recommended per-core Curve Optimizer offsets (-15 to -30 typical) for stable under-volting. UI hint only — doesn't change BIOS.", badge: "MODERN", impact: "MED", nativeAction: {"powershell":"# No-op — UI banner only; CO is BIOS-only","type":"tool","params":{"kind":"uiBanner","topic":"zen5-co"}} },
  { id: "Zen5PBOScalarLock", category: "registry", safety: "safe", plainEnglish: "Caps Zen 5 PBO boost at 1x — better thermals + chip longevity.", verifiedOn: { win10: true, win11: true }, title: "Zen 5: Lock PBO Scalar at 1x (longevity)", description: "Pins the PBO scalar at 1x in the AMD power profile to stop the CPU from over-boosting (which hurts longevity on Zen 5). Best for daily-driver Ryzen 9000.", badge: "MODERN", impact: "LOW", nativeAction: {"powershell":"# Applied via amd-power-profile XML — see template","type":"powerCfg","params":{"kind":"pboScalar","value":1}} },
  { id: "Zen5SMTSchedulerHint", category: "registry", safety: "safe", plainEnglish: "Hints Windows to spread game threads across physical Zen 5 cores first.", verifiedOn: { win10: true, win11: true }, title: "Zen 5: SMT Scheduler Hint (Game-Friendly)", description: "Sets HeteroPolicyInEffect=4 + Win11ProcessorIdleMin=1 to favor 1 thread per Zen 5 core for game threads (better than naive SMT spread).", badge: "MODERN", impact: "MED", recommended: true, nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Power' -Name 'HeteroPolicyInEffect' -Value 4 -Type DWord","type":"registry","params":{"hive":"HKLM","path":"SYSTEM\\CurrentControlSet\\Control\\Power","name":"HeteroPolicyInEffect","value":4,"type":"REG_DWORD"}} },
  { id: "Zen5AGESACStatePolicy", category: "registry", safety: "safe", plainEnglish: "Auto-tunes Zen 5 C-States to avoid the early-AGESA stutter bugs.", verifiedOn: { win10: true, win11: true }, title: "Zen 5: AGESA-Aware C-State Policy", description: "Detects AGESA microcode level and applies the right C-State min/max policy for your specific Zen 5 build — avoids the early-AGESA C-State stutter bugs.", badge: "MODERN", impact: "MED", nativeAction: {"powershell":"# Applied via powercfg /setacvalueindex bulk — see template","type":"powerCfg","params":{"kind":"cStatePolicy","auto":true}} },
  { id: "Zen5X3DCachePin", category: "registry", safety: "safe", plainEnglish: "Pins games to the 3D V-Cache CCD on 9800X3D / 9950X3D chips.", verifiedOn: { win10: true, win11: true }, title: "Zen 5 X3D: Pin Games to V-Cache CCD (9800X3D / 9950X3D)", description: "Detects 9800X3D / 9950X3D and pins game executables to the V-Cache CCD via Game Bar Process Group registry. Big wins on dual-CCD X3D parts.", badge: "MODERN", impact: "HIGH", recommended: true, nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\GameBar' -Name 'PreferredCcd' -Value 0 -Type DWord","type":"registry","params":{"hive":"HKLM","path":"SOFTWARE\\Microsoft\\Windows\\GameBar","name":"PreferredCcd","value":0,"type":"REG_DWORD"}} },
  { id: "ArrowAPOOptIn", category: "registry", safety: "safe", plainEnglish: "Opts you into Intel APO — Microsoft + Intel game scheduler for Core Ultra 2.", verifiedOn: { win10: true, win11: true }, title: "Arrow Lake: Intel APO Opt-In", description: "Enables Intel Application Optimization (APO) for Arrow Lake — the Microsoft-Intel co-developed scheduler that boosts AAA games on Core Ultra 2.", badge: "MODERN", impact: "HIGH", recommended: true, nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Intel\\APO' -Name 'Enabled' -Value 1 -Type DWord","type":"registry","params":{"hive":"HKLM","path":"SOFTWARE\\Intel\\APO","name":"Enabled","value":1,"type":"REG_DWORD"}} },
  { id: "ArrowThreadDirectorHint", category: "registry", safety: "safe", plainEnglish: "Tells Thread Director to keep game threads on the fast P-cores.", verifiedOn: { win10: true, win11: true }, title: "Arrow Lake: Thread Director Game Hint", description: "Sets Win11's HeteroPolicyInEffect to 'Prefer P-cores for foreground' on Arrow Lake — stops the scheduler from parking game threads on E-cores mid-frame.", badge: "MODERN", impact: "HIGH", recommended: true, nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Power' -Name 'HeteroPolicyInEffect' -Value 5 -Type DWord","type":"registry","params":{"hive":"HKLM","path":"SYSTEM\\CurrentControlSet\\Control\\Power","name":"HeteroPolicyInEffect","value":5,"type":"REG_DWORD"}} },
  { id: "ArrowEcoreParkPolicy", category: "registry", safety: "aggressive", plainEnglish: "Parks Arrow Lake E-cores while gaming so all threads land on P-cores.", verifiedOn: { win10: true, win11: true }, title: "Arrow Lake: Park E-Cores During Games", description: "Parks all E-cores when a known game process is in the foreground — eliminates Thread Director thrash. Re-parks dynamically when the game closes.", badge: "MODERN", impact: "MED", nativeAction: {"powershell":"# Applies via powercfg / Process Lasso CPU affinity rule","type":"powerCfg","params":{"kind":"ecorePark","whileGameForeground":true}} },
  { id: "ArrowLunarLakePowerPlan", category: "registry", safety: "safe", plainEnglish: "Switches Lunar Lake laptops to Intel's performance plan (no iGPU down-clock).", verifiedOn: { win10: true, win11: true }, title: "Lunar Lake (Core Ultra 200V): Performance Power Plan", description: "Activates the Intel-tuned Lunar Lake performance plan — fixes the default's aggressive iGPU down-clock that costs ~10% FPS in handheld games.", badge: "MODERN", impact: "MED", nativeAction: {"powershell":"powercfg -setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c","type":"powerCfg","params":{"kind":"powerPlanGuid","guid":"8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"}} },
  { id: "ArrowITDTelemetryOff", category: "registry", safety: "aggressive", plainEnglish: "Turns off Intel Thread Director telemetry uploads.", verifiedOn: { win10: true, win11: true }, title: "Arrow Lake: ITD Telemetry OFF", description: "Disables Intel Thread Director telemetry uploads — stops background CPU sampling that adds ~0.5% overhead.", badge: "MODERN", impact: "LOW", nativeAction: {"powershell":"Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Intel\\TelemetryService' -Name 'Enabled' -Value 0 -Type DWord","type":"registry","params":{"hive":"HKLM","path":"SOFTWARE\\Intel\\TelemetryService","name":"Enabled","value":0,"type":"REG_DWORD"}} },
  // V4 — COD Advanced Optimizations
  { id: "CodDisableTelemetry", category: "registry", safety: "safe", plainEnglish: "Call of Duty tweak — blocks Activision analytics from sending data mid-game.", verifiedOn: { win10: true, win11: true }, title: "Block Activision Telemetry + Crash Reporters", description: "Stops background Activision/Battle.net analytics tasks and blocks crash telemetry endpoints (crash.callofduty.com, analytics.callofduty.com) via hosts file. Eliminates mid-game CPU/network spikes from periodic telemetry uploads.", badge: "UNIVERSAL", impact: "MED", recommended: true },
  { id: "CodTdrDelay", category: "registry", safety: "safe", plainEnglish: "Call of Duty tweak — prevents fake GPU crash errors during shader loading.", verifiedOn: { win10: true, win11: true }, title: "Extend GPU TDR Delay to 8s (Shader Compile Crash Fix)", description: "Extends Windows GPU Timeout Detection from 2s to 8s. BO6/Warzone shader compilation during level loads can exceed the 2s window on 4-8GB GPUs, triggering false 'GPU stopped responding' crashes. Extending to 8s prevents this without stability risk. Reboot required.", badge: "RECOMMENDED", impact: "MED", recommended: true },
{ id: "CodMMCSS", category: "registry", safety: "safe", plainEnglish: "Call of Duty tweak — restore balanced game scheduling for Windows.", verifiedOn: { win10: true, win11: true }, title: "Keep MMCSS and Desktop Responsive", description: "Restores balanced Games scheduling so DWM, input, audio, and Alt-Tab are not starved by an aggressive Priority 6/GPU 8 override.", badge: "STABILITY", impact: "MED", recommended: true },
  { id: "CodQoSPolicy", category: "registry", safety: "safe", plainEnglish: "Call of Duty tweak — tells your router to prioritize COD network packets.", verifiedOn: { win10: true, win11: true }, title: "QoS Policy — Mark COD Packets as High Priority (DSCP 46)", description: "Creates Windows QoS policies marking cod.exe UDP and TCP traffic with DSCP 46 (Expedited Forwarding). Routers that honor DSCP will prioritize COD packets over background downloads and Discord traffic, reducing jitter during Warzone drops.", badge: "NETWORK", impact: "MED", recommended: false },
{ id: "CodFramePacing", category: "registry", safety: "safe", plainEnglish: "Call of Duty tweak — remove undocumented frame-queue overrides.", verifiedOn: { win10: true, win11: true }, title: "Restore Stable DXGI Frame Pacing", description: "Removes custom WaitableObject and FlipModel overrides and uses a moderate two-frame target to avoid blocking menu rendering or Alt-Tab.", badge: "STABILITY", impact: "MED", recommended: true },
  { id: "CodMemPriority", category: "registry", safety: "safe", plainEnglish: "Call of Duty tweak — keeps COD textures in RAM so Windows doesn't page them out mid-game.", verifiedOn: { win10: true, win11: true }, title: "COD Memory Priority — Lock Working Set (All Executables)", description: "Sets PagePriority=5 and WorkingSetPolicy=1 (locked) for all COD exe variants via IFEO. Prevents Windows from paging out COD texture streaming cache during background bursts — eliminates the 200-500ms stutter when BO6 re-fetches paged-out map assets.", badge: "32GB RAM", impact: "HIGH", recommended: true },
  // 4th–8th gen Intel (Haswell / Broadwell / Skylake / Kaby Lake / Coffee Lake)
  { id: "IntelOldGenPowerOpt", category: "registry", safety: "safe", plainEnglish: "Keeps all 4 cores at max clock speed for the entire gaming session on 4th–8th gen Intel CPUs.", verifiedOn: { win10: true, win11: true }, title: "Intel 4th–8th Gen: Disable CPU Frequency Scaling + Power Throttle", description: "Activates the High Performance power plan and locks CPU Min/Max processor state to 100%. Also disables Windows Power Throttling (PowerThrottlingOff=1) — Windows 10 can silently reduce clock speed for 'background' processes including the game. On older Intel CPUs (Haswell through Coffee Lake) with no speed-shift hardware assist, this prevents the 50–150ms frequency ramp-up delay that causes frame-time spikes when you first start shooting. Pair with Disable Core Parking for maximum effect.", badge: "Intel 4th–8th Gen", impact: "HIGH", recommended: true },
  // ── Mouse tweaks ────────────────────────────────────────────────────────────
  { id: "MousePointerSpeed611",   category: "mouse",    safety: "safe", plainEnglish: "Sets pointer speed to 6/11 neutral baseline — no acceleration distortion.", verifiedOn: { win10: true, win11: true }, title: "Set Pointer Speed to 6/11 (Neutral Baseline)", description: "Sets MouseSensitivity=10 — the neutral 6 out of 11 notches in Windows settings. Ensures your in-game sensitivity matches your real mouse movement with zero acceleration curve distortion.", badge: "RECOMMENDED", impact: "HIGH", recommended: true },
  { id: "MouseDataQueueSize",     category: "mouse",    safety: "safe", plainEnglish: "Reduces mouse input buffer from 100 to 20 entries for lower click latency.", verifiedOn: { win10: true, win11: true }, title: "Reduce Mouse Input Buffer (mouclass)", description: "Sets MouseDataQueueSize=20 in the mouclass driver (default 100). Smaller buffer means Windows processes mouse events with less queuing delay — lower click-to-action latency.", badge: "RECOMMENDED", impact: "HIGH", recommended: true },
  { id: "MouseHoverTimeMin",      category: "mouse",    safety: "safe", plainEnglish: "Sets mouse hover time to 10ms for instant tooltip/menu response.", verifiedOn: { win10: true, win11: true }, title: "Minimize Mouse Hover Time (10ms)", description: "Sets MouseHoverTime=10ms (default 400ms) — menus and tooltips respond instantly on hover. Reduces perceived UI delay.", impact: "MED" },
  { id: "MouseHIDPowerSave",      category: "mouse",    safety: "safe", plainEnglish: "Disables USB power management for all HID mouse devices.", verifiedOn: { win10: true, win11: true }, title: "Disable Mouse HID Power Management", description: "Sets EnhancedPowerManagementEnabled=0 on every detected mouse device — prevents USB controller from sleeping the mouse port, eliminating the 5–50ms wake latency before your first click registers.", badge: "RECOMMENDED", impact: "HIGH", recommended: true },
  // ── Keyboard tweaks ──────────────────────────────────────────────────────────
  { id: "KeyboardRepeatRateMax",    category: "keyboard", safety: "safe", plainEnglish: "Sets keyboard repeat rate to maximum for fastest key repeat.", verifiedOn: { win10: true, win11: true }, title: "Maximum Keyboard Repeat Rate", description: "Sets KeyboardSpeed=31 (maximum) — key repeat fires at ~30 chars/sec instead of the default ~10/sec. Makes held keys respond instantly in any application.", badge: "RECOMMENDED", impact: "MED", recommended: true },
  { id: "KeyboardRepeatDelayMin",   category: "keyboard", safety: "safe", plainEnglish: "Sets keyboard repeat delay to minimum (250ms) before repeat kicks in.", verifiedOn: { win10: true, win11: true }, title: "Minimum Keyboard Repeat Delay", description: "Sets KeyboardDelay=0 (250ms before repeat starts, vs default 500ms). Hold any key and it starts repeating twice as fast.", badge: "RECOMMENDED", impact: "MED", recommended: true },
  { id: "KeyboardDisableFilterKeys",category: "keyboard", safety: "safe", plainEnglish: "Disables Filter Keys which adds deliberate artificial keystroke delays.", verifiedOn: { win10: true, win11: true }, title: "Disable Filter Keys (Remove Artificial Delay)", description: "Filter Keys deliberately delays keystroke registration. It adds latency even when you don't know it's on. Disabling it removes all artificial keystroke delay.", badge: "RECOMMENDED", impact: "HIGH", recommended: true },
  { id: "KeyboardDisableStickyKeys",category: "keyboard", safety: "safe", plainEnglish: "Disables Sticky Keys popup that interrupts gameplay on Shift press.", verifiedOn: { win10: true, win11: true }, title: "Disable Sticky Keys Shortcut", description: "Disables the Sticky Keys popup (triggered by pressing Shift 5 times). In games that need rapid Shift (sprint, crouch, slide), this popup can pause or alt-tab your game.", badge: "RECOMMENDED", impact: "HIGH", recommended: true },
  { id: "KeyboardDataQueueSize",    category: "keyboard", safety: "safe", plainEnglish: "Reduces keyboard input buffer from 100 to 20 entries for lower key latency.", verifiedOn: { win10: true, win11: true }, title: "Reduce Keyboard Input Buffer (kbdclass)", description: "Sets KeyboardDataQueueSize=20 in the kbdclass driver (default 100). Smaller buffer means keystrokes are processed with less queuing overhead — lower key-to-action latency.", impact: "MED" },
  { id: "KeyboardHIDPowerSave",     category: "keyboard", safety: "safe", plainEnglish: "Disables USB power management for all HID keyboard devices.", verifiedOn: { win10: true, win11: true }, title: "Disable Keyboard HID Power Management", description: "Sets EnhancedPowerManagementEnabled=0 on every detected keyboard — prevents USB controller from suspending your keyboard port, eliminating first-keypress wake latency.", impact: "MED" },
];

export const TWEAK_BY_ID: Map<string, TweakMeta> = new Map(
    TWEAK_REGISTRY.map((t) => [t.id, t])
);

export function getTweakMeta(id: string): TweakMeta | undefined {
    return TWEAK_BY_ID.get(id);
}

export function tweaksByCategory(category: TweakCategory): TweakMeta[] {
    return TWEAK_REGISTRY.filter((t) => t.category === category);
}

export const TOTAL_TWEAK_COUNT = TWEAK_REGISTRY.length;

export const SAFETY_LABEL: Record<TweakSafety, string> = {
    safe: "Safe",
    aggressive: "Aggressive",
    expert: "Expert",
};

// ── V2.2 reapplicable driver tweaks (Task #50) ────────────────────────────
// Registered here so they pick up the same plain-English / safety / tooltip
// metadata pipeline the rest of the app uses through TweakRow + smart-rec.
const V22_DRIVER_TWEAKS: Array<{ id: string; category: TweakCategory; safety?: TweakSafety; plainEnglish?: string; verifiedOn?: { win10: boolean; win11: boolean }; title: string; description: string; badge?: string; impact: TweakImpact; warning?: string }> = [
    { id: "NvTextureFilterHighPerf", category: "nvidia", title: "NVIDIA Texture Filtering = High Performance", description: "Writes PS_TexFilterQuality=0 etc. to NVIDIA Corporation\\Global\\NVTweak. Equivalent to NVCP 'Texture Filtering Quality: High Performance'.", badge: "RECOMMENDED", impact: "MED" },
    { id: "NvLowLatencyUltra",       category: "nvidia", title: "NVIDIA Low Latency Mode = Ultra",            description: "RmLowLatencyMode=2 + FlipQueueSize=1. Lowest possible input-to-photon latency via global profile.", badge: "RECOMMENDED", impact: "HIGH" },
    { id: "NvThreadedOptOn",         category: "nvidia", title: "NVIDIA Threaded Optimization = ON",          description: "Forces OGL_ThreadControl/D3D_ThreadControl=1 globally — driver-side thread offload.", badge: "RECOMMENDED", impact: "MED" },
    { id: "NvPowerMgmtMax",          category: "nvidia", title: "NVIDIA Power Management = Max Performance",  description: "Locks PowerMizer to P0 — no per-frame power-state stutter.", badge: "RECOMMENDED", impact: "HIGH" },
    { id: "AmdTextureFilterPerf",    category: "amd",    title: "AMD Texture Filtering = Performance",        description: "CatalystAI=0/TFQ=0/TextureOpt=1 — Adrenalin 'Performance' texture quality.", badge: "RECOMMENDED", impact: "MED" },
    { id: "AmdSurfaceFormatOpt",     category: "amd",    title: "AMD Surface Format Optimization = ON",       description: "EnableSurfaceFormatReplacements=1 + KMD_EnableSFR=1.", badge: "RECOMMENDED", impact: "MED" },
    { id: "AmdTessOverride16x",      category: "amd",    title: "AMD Tessellation = AMD Optimized (16x cap)", description: "Caps tessellation at 16x on legacy titles where game-side tessellation is wasteful.", badge: "RECOMMENDED", impact: "MED" },
    { id: "AmdRadeonBoostOff",       category: "amd",    title: "AMD Radeon Boost = OFF (force disable)",     description: "Disables Radeon Boost via registry. Use when Boost causes texture pop in competitive shooters.", badge: "OPTIONAL", impact: "LOW" },
    { id: "AmdFRTC60",               category: "amd",    title: "AMD Frame Rate Target Control = 60 FPS",     description: "Adrenalin FRTC capped at 60.", badge: "60Hz",  impact: "MED" },
    { id: "AmdFRTC144",              category: "amd",    title: "AMD Frame Rate Target Control = 144 FPS",    description: "Adrenalin FRTC capped at 144.", badge: "144Hz", impact: "MED" },
    { id: "AmdFRTC240",              category: "amd",    title: "AMD Frame Rate Target Control = 240 FPS",    description: "Adrenalin FRTC capped at 240.", badge: "240Hz", impact: "MED" },
    { id: "EnableNvidiaMSIPro",      category: "nvidia",   title: "NVIDIA MSI Mode (single-adapter verified)", description: "Pro-only action. Enumerates live Windows display devices, requires exactly one active NVIDIA adapter with a verifiable MSI capability, and writes/verifies only MSISupported=1. Refuses hybrid or ambiguous display topologies; never touches NICs, NVMe, affinity, or priority.", badge: "PRO · VERIFIED", impact: "HIGH", safety: "expert" },
    { id: "NvidiaD3DOptimize",       category: "nvidia",   title: "NVIDIA DirectX: Debug Layers OFF + Async Shader Compile", description: "Disables DX11/12 debug and validation layers (ForceDebugRuntime=0, LoadDebugRuntime=0) — eliminates 10–30% CPU overhead if accidentally enabled. Enables async shader compilation to remove compile-stall stutters in COD/FiveM/Fortnite on GTX 1650 Super.", badge: "RECOMMENDED", impact: "HIGH" },
    { id: "NvidiaPCIeGen3Force",     category: "nvidia",   title: "NVIDIA PCIe Gen3 Lock + GPU Preemption",  description: "Writes PCIELinkSpeedOverride=2 to the NVIDIA GPU class key — prevents driver from falling back to PCIe 2.0 x8 mode under power transitions, which halves GPU memory bandwidth. Also enables GPU preemption for smoother DPC scheduling.", badge: "GTX 1650", impact: "MED" },
    { id: "NvidiaInterruptAffinity", category: "nvidia",   title: "NVIDIA Interrupt Affinity → CPU Core 2",  description: "Routes GPU DPC interrupts to CPU core 2 (TargetedProcessors=4, AssignmentPolicy=1) to reduce contention with OS scheduler on core 0. Does NOT touch DevicePolicy/DevicePriority (the V1 BSOD keys). Ryzen 5 3500 specific.", badge: "ADVANCED",  impact: "MED" },
    { id: "AmdD3DOptimize",          category: "amd",      title: "AMD DirectX: Debug Layers OFF + Async Shader Compile", description: "Disables D3D debug/validation layers and enables async shader compilation for AMD. Also sets DXGI WaitableObjectsThreshold=1 for frame pacing stability on RDNA1/2/Polaris.", badge: "RECOMMENDED", impact: "HIGH" },
    { id: "AmdPCIeOptimize",         category: "amd",      title: "AMD Async Compute + PCIe Preemption",     description: "Sets KMD_EnableAsyncCompute=1, clears FRTC driver flag, and enables GPU preemption — optimizes Radeon async compute dispatch and ensures full PCIe bandwidth.", badge: "RECOMMENDED", impact: "MED" },
    // CPU tab tweaks
    { id: "CpuBoostModeAggressive",    category: "registry", title: "Processor Performance Boost Mode = Aggressive", description: "Sets the Processor Performance Boost Mode powercfg GUID to 2 (Aggressive). CPU ramps to maximum boost frequency instantly on any load spike — eliminates frequency-ramp delay that causes frame drops at firefight starts.", badge: "RECOMMENDED", impact: "HIGH" },
    { id: "CpuIdleMin100",             category: "registry", title: "Minimum Processor State = 100% (No C-States)", description: "Forces CPU minimum processor state to 100% via powercfg — prevents the processor from downclocking at idle. Eliminates 1–2ms frequency wake-up latency on Ryzen.", impact: "MED" },
    { id: "CpuFortniteIFEO",           category: "registry", title: "Fortnite — IFEO AboveNormal CPU + IO Priority", description: "Writes IFEO PerfOptions for FortniteClient-Win64-Shipping.exe, FortniteLauncher.exe, EpicGamesLauncher.exe: CpuPriorityClass=3, CpuPriorityBoost, ForceForegroundBoost, IoPriority=2, GpuPriority=8.", badge: "FORTNITE", impact: "HIGH" },
    { id: "CpuCodIFEO",               category: "registry", title: "Call of Duty — IFEO AboveNormal CPU + IO Priority", description: "Writes IFEO PerfOptions for cod.exe, BlackOpsColdWar.exe, ModernWarfare.exe, MW2, MW3, Warzone.exe, MWIII.exe: AboveNormal CPU priority, boost on, energy throttle off, IoPriority=2.", badge: "COD", impact: "HIGH" },
    { id: "CpuGenericGameIFEO",        category: "registry", title: "CS2 / Valorant / Apex / Tarkov / PUBG / Rust — IFEO Boost", description: "Writes AboveNormal IFEO priority for cs2.exe, valorant.exe, r5apex.exe, EscapeFromTarkov.exe, pubg.exe, RustClient.exe, RainbowSix.exe, Overwatch.exe — schedules these games above all background apps.", badge: "MULTI-GAME", impact: "HIGH" },
    { id: "CpuDisableSpectreMitigation", category: "registry", safety: "expert" as const, plainEnglish: "Disables Spectre/Meltdown CPU security mitigations for 2–8% more CPU performance. Only safe on isolated offline gaming rigs.", verifiedOn: { win10: true, win11: true }, title: "Disable Spectre/Meltdown Mitigations (Expert Only)", description: "Sets FeatureSettingsOverride=3 + FeatureSettingsOverrideMask=3 — disables Spectre v1/v2 and Meltdown kernel mitigations. Recovers 2–8% CPU latency. ONLY safe on isolated offline gaming PCs.", badge: "EXPERT", impact: "HIGH", warning: "⚠ Disabling Spectre/Meltdown mitigations exposes the CPU to kernel memory disclosure attacks. Only enable on a fully offline gaming rig with no sensitive data." },
    // Discord While Gaming — gaming session tweaks
    { id: "DiscordDisableRichPresence", category: "discord", title: "Disable Game Activity Scanner (Rich Presence)", description: "Sets detectPlatformGames: false + showCurrentGame: false in settings.json — stops Discord polling every running process every few seconds to detect games. Removes recurring CPU overhead of the RPC scanner.", badge: "RECOMMENDED", impact: "MED" },
    { id: "DiscordDisableGifAutoplay",  category: "discord", title: "Disable GIF & Animated Emoji Autoplay",         description: "Sets gifAutoPlay: false, animatedEmojiAutoplay: false, showEmojiSuggestions: false — stops Discord rendering looping GIFs and bouncing animated emoji. Each animated frame is a GPU draw call; disabling cuts this entirely.", badge: "RECOMMENDED", impact: "MED" },
    { id: "DiscordMinimizeBgLoad",      category: "discord", title: "Minimize Background Media & Rendering Load",    description: "Sets inlineAttachmentMedia: false, renderSpoilers: ON_CLICK, showMemberListAvatars: false — stops Discord preloading image/video attachments inline and rendering member avatars. Reduces background network fetches and GPU compositing.", badge: "RECOMMENDED", impact: "MED" },
    { id: "DiscordSuppressNotifications", category: "discord", title: "Suppress Notification Toasts During Gaming",  description: "Sets notifyFriendsOnline: false + notifyTyping: false in settings.json. Also applies Windows NOC_GLOBAL_SETTING_ALLOW_TOASTS_ABOVE_LOCK registry flag to suppress toasts when in a fullscreen game.", impact: "MED" },
    { id: "DiscordDisableSpellcheck",   category: "discord", title: "Disable Spellcheck Worker",                    description: "Sets enableSpellCheck: false in settings.json — kills Discord's background spell analysis process that runs on every keystroke in a text box.", impact: "LOW" },
];
{
    const existingIds = new Set(TWEAK_REGISTRY.map(m => m.id));
    for (const t of V22_DRIVER_TWEAKS) {
        if (existingIds.has(t.id)) continue;
        TWEAK_REGISTRY.push({
            id: t.id, category: t.category, safety: "safe",
            plainEnglish: t.description, verifiedOn: { win10: true, win11: true },
            title: t.title, description: t.description,
            badge: t.badge, impact: t.impact,
        });
    }
}

export const SAFETY_DESCRIPTION: Record<TweakSafety, string> = {
    safe: "Reversible, broadly compatible. Safe defaults.",
    aggressive: "Bigger gains, but touches services/features some users want. Read the description.",
    expert: "Powerful but risky — can break boot, security, or driver stability if you don't understand it.",
};
