#Requires -RunAsAdministrator
# ============================================================
#  Opti Gods — Call of Duty Optimizer
#  Rig: AMD Ryzen 9 9800X3D  |  NVIDIA RTX 5070  |  32GB RAM
#  Profile: STREAMER-SAFE (OBS-friendly, no priority wars)
#  Generated by leaq via optigods.com
# ============================================================

$ErrorActionPreference = "SilentlyContinue"

Write-Host ""
Write-Host "  OPTI GODS — COD Optimizer" -ForegroundColor Red
Write-Host "  Rig: 9800X3D + RTX 5070 + 32GB  |  Streamer Profile" -ForegroundColor DarkGray
Write-Host ""

# ─────────────────────────────────────────────────────────────
#  STEP 1 — UNDO: Remove High Priority IFEO entry for cod.exe
#  (Fixes the lag you were getting while streaming)
# ─────────────────────────────────────────────────────────────
Write-Host "[1/7] Removing cod.exe High Priority IFEO entry..." -ForegroundColor Yellow
$ifeo = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\cod.exe\PerfOptions'
If (Test-Path $ifeo) {
    Remove-Item -Path $ifeo -Force -Recurse
    Write-Host "      [FIXED] IFEO priority override removed — cod.exe back to default priority." -ForegroundColor Green
} Else {
    Write-Host "      [OK] No IFEO override found (already clean)." -ForegroundColor DarkGray
}

# ─────────────────────────────────────────────────────────────
#  STEP 2 — Network Buffers (universal, streamer-safe)
# ─────────────────────────────────────────────────────────────
Write-Host "[2/7] Optimizing network socket buffers..." -ForegroundColor Yellow
Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\AFD\Parameters' -Name 'DefaultReceiveWindow' -Value 524288 -Type DWord -Force
Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\AFD\Parameters' -Name 'DefaultSendWindow'   -Value 524288 -Type DWord -Force
Write-Host "      [OK] Socket buffers 512KB — reduces Warzone BR drop-phase packet loss." -ForegroundColor Green

# ─────────────────────────────────────────────────────────────
#  STEP 3 — Disable LSO + TCP No-Delay (hit reg / desync fix)
# ─────────────────────────────────────────────────────────────
Write-Host "[3/7] Applying TCP optimizations..." -ForegroundColor Yellow
$adapters = Get-NetAdapterAdvancedProperty -DisplayName "*Large Send Offload*" -EA SilentlyContinue
foreach ($a in $adapters) {
    Disable-NetAdapterLso -Name $a.Name -EA SilentlyContinue
}
$tcpPath = 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters'
Set-ItemProperty -Path $tcpPath -Name 'TCPNoDelay'       -Value 1 -Type DWord -Force
Set-ItemProperty -Path $tcpPath -Name 'TcpAckFrequency'  -Value 1 -Type DWord -Force
Set-ItemProperty -Path $tcpPath -Name 'Tcp1323Opts'      -Value 0 -Type DWord -Force
Write-Host "      [OK] LSO disabled, TCP no-delay + immediate ACKs — tighter server tick alignment." -ForegroundColor Green

# ─────────────────────────────────────────────────────────────
#  STEP 4 — AMD Ryzen 9800X3D: Power Plan + Core Unpark
# ─────────────────────────────────────────────────────────────
Write-Host "[4/7] Configuring AMD Ryzen 9800X3D power settings..." -ForegroundColor Yellow
$ryzen = powercfg -l | Select-String 'Ryzen'
If ($ryzen) {
    $guid = (($ryzen.Line.Trim()) -split '\s+')[3]
    powercfg -setactive $guid 2>$null
    Write-Host "      [OK] AMD Ryzen Balanced power plan activated — correct boost clock behavior for 9800X3D." -ForegroundColor Green
} Else {
    powercfg -setacvalueindex SCHEME_CURRENT 54533251-82be-4824-96c1-47b60b740d00 be337238-0d82-4146-a960-4f3749d470c7 0
    powercfg -setacvalueindex SCHEME_CURRENT 54533251-82be-4824-96c1-47b60b740d00 943c8cb6-6f93-4227-ad87-e9a3feec08d1 100
    powercfg -setactive SCHEME_CURRENT
    Write-Host "      [OK] CPU min 0% / max 100% — 9800X3D will sustain full boost during BO6." -ForegroundColor Green
}
$cpPath = 'HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583'
If (Test-Path $cpPath) {
    Set-ItemProperty -Path $cpPath -Name 'ValueMax'   -Value 0 -Type DWord -Force
    Set-ItemProperty -Path $cpPath -Name 'Attributes' -Value 1 -Type DWord -Force
}
powercfg -setacvalueindex SCHEME_CURRENT 54533251-82be-4824-96c1-47b60b740d00 0cc5b647-c1df-4637-891a-dec35c318583 100 2>$null
Write-Host "      [OK] All 16 threads unparked — no core wake latency during BO6 threading bursts." -ForegroundColor Green

# ─────────────────────────────────────────────────────────────
#  STEP 5 — NVIDIA RTX 5070: Low Latency + Disable Ansel
# ─────────────────────────────────────────────────────────────
Write-Host "[5/7] Applying NVIDIA RTX 5070 driver tweaks..." -ForegroundColor Yellow
$nvKey = 'HKLM:\SYSTEM\CurrentControlSet\Services\nvlddmkm'
If (Test-Path $nvKey) {
    Set-ItemProperty -Path $nvKey -Name 'NvCplLowLatencyMode' -Value 1 -Type DWord -Force
    Write-Host "      [OK] NVIDIA Low Latency mode — pre-rendered frame queue 3→1, lower input lag in gunfights." -ForegroundColor Green
} Else {
    Write-Host "      [SKIP] NVIDIA driver key not found." -ForegroundColor DarkGray
}
$ansel = 'HKLM:\SOFTWARE\NVIDIA Corporation\Global\Ansel'
If (Test-Path $ansel) {
    Set-ItemProperty -Path $ansel -Name 'AnselEnable' -Value 0 -Type DWord -Force
    Write-Host "      [OK] NVIDIA Ansel disabled — removes overlay hook from every DirectX process." -ForegroundColor Green
}

# ─────────────────────────────────────────────────────────────
#  STEP 6 — Clear Shader Cache + GPU Driver Cache
# ─────────────────────────────────────────────────────────────
Write-Host "[6/7] Clearing shader + GPU driver cache..." -ForegroundColor Yellow
$cachePaths = @(
    "$env:LOCALAPPDATA\Activision\cod\cache",
    "$env:LOCALAPPDATA\Battle.net\Cache",
    "$env:LOCALAPPDATA\NVIDIA\DXCache",
    "$env:LOCALAPPDATA\D3DSCache"
)
$cleaned = 0
foreach ($p in $cachePaths) {
    If (Test-Path $p) {
        Remove-Item -Path "$p\*" -Recurse -Force -EA SilentlyContinue
        $cleaned++
        Write-Host "      Cleared: $p" -ForegroundColor Cyan
    }
}
Write-Host "      [OK] $cleaned cache folders cleared. BO6 will recompile shaders on next launch (2-3 min stutter, then fixed)." -ForegroundColor Green

# ─────────────────────────────────────────────────────────────
#  STEP 7 — Disable Xbox DVR Capture Hooks
# ─────────────────────────────────────────────────────────────
Write-Host "[7/7] Disabling Xbox DVR capture hooks..." -ForegroundColor Yellow
Set-ItemProperty -Path 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR' -Name 'AppCaptureEnabled' -Value 0 -Type DWord -Force
Set-ItemProperty -Path 'HKCU:\System\GameConfigStore' -Name 'GameDVR_Enabled'              -Value 0 -Type DWord -Force
Set-ItemProperty -Path 'HKCU:\System\GameConfigStore' -Name 'GameDVR_HonorUserFSEBehaviorMode' -Value 1 -Type DWord -Force
Write-Host "      [OK] Xbox background capture thread removed from DirectX hook." -ForegroundColor Green

# ─────────────────────────────────────────────────────────────
#  DONE
# ─────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ✓ All done! What was applied:" -ForegroundColor Red
Write-Host "    • IFEO priority override removed (stream lag fix)" -ForegroundColor White
Write-Host "    • Network buffers 512KB + LSO off + TCP no-delay" -ForegroundColor White
Write-Host "    • AMD Ryzen Balanced power plan + all cores unparked" -ForegroundColor White
Write-Host "    • NVIDIA Low Latency mode + Ansel disabled" -ForegroundColor White
Write-Host "    • Shader + driver cache cleared" -ForegroundColor White
Write-Host "    • Xbox DVR hooks disabled" -ForegroundColor White
Write-Host ""
Write-Host "  What was intentionally skipped (streamer-safe):" -ForegroundColor DarkGray
Write-Host "    • High CPU priority for cod.exe  — causes OBS stutter" -ForegroundColor DarkGray
Write-Host "    • Windows Game Mode              — deprioritizes OBS" -ForegroundColor DarkGray
Write-Host "    • HAGS disable                  — RTX 5070 runs better WITH HAGS on" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  Restart COD. No reboot required." -ForegroundColor Yellow
Write-Host ""
