// 200+ game executables shipped to Opti Gods' Process Lasso ProBalance whitelist.
// Each entry: { exe, title, genre } — used to render the toggleable list in
// the Process Lasso accordion and to feed the future Tauri exec engine.
// V2 — Task #38.

export interface WhitelistedGame {
  exe: string;
  title: string;
  genre:
    | "FPS" | "BR" | "MOBA" | "RPG" | "MMO" | "Racing" | "Sandbox"
    | "Survival" | "Fighting" | "Strategy" | "Sim" | "Sports" | "Horror"
    | "Action" | "Platformer" | "Roguelike" | "Other";
}

export const GAME_WHITELIST: WhitelistedGame[] = [
  // ─── Competitive Shooters ───
  { exe: "VALORANT-Win64-Shipping.exe", title: "Valorant", genre: "FPS" },
  { exe: "cs2.exe", title: "Counter-Strike 2", genre: "FPS" },
  { exe: "csgo.exe", title: "CS:GO (legacy)", genre: "FPS" },
  { exe: "r5apex.exe", title: "Apex Legends", genre: "BR" },
  { exe: "r5apex_dx12.exe", title: "Apex Legends (DX12)", genre: "BR" },
  { exe: "ModernWarfare.exe", title: "Call of Duty: MW", genre: "FPS" },
  { exe: "BlackOps6.exe", title: "Call of Duty: BO6", genre: "FPS" },
  { exe: "cod.exe", title: "Call of Duty (launcher)", genre: "FPS" },
  { exe: "warzone.exe", title: "Warzone", genre: "BR" },
  { exe: "RainbowSix.exe", title: "Rainbow Six Siege", genre: "FPS" },
  { exe: "RainbowSix_Vulkan.exe", title: "Siege (Vulkan)", genre: "FPS" },
  { exe: "Overwatch.exe", title: "Overwatch 2", genre: "FPS" },
  { exe: "FortniteClient-Win64-Shipping.exe", title: "Fortnite", genre: "BR" },
  { exe: "FortniteLauncher.exe", title: "Fortnite Launcher", genre: "BR" },
  { exe: "EscapeFromTarkov.exe", title: "Escape From Tarkov", genre: "FPS" },
  { exe: "TslGame.exe", title: "PUBG: BG", genre: "BR" },
  { exe: "Hunt  Showdown.exe", title: "Hunt: Showdown", genre: "FPS" },
  { exe: "BattleBit.exe", title: "BattleBit Remastered", genre: "FPS" },
  { exe: "FinalsClient-Win64-Shipping.exe", title: "THE FINALS", genre: "FPS" },
  { exe: "Marvel-Win64-Shipping.exe", title: "Marvel Rivals", genre: "FPS" },
  { exe: "ARC-Win64-Shipping.exe", title: "ARC Raiders", genre: "FPS" },
  { exe: "Splitgate2-Win64-Shipping.exe", title: "Splitgate 2", genre: "FPS" },
  { exe: "XDefiant.exe", title: "XDefiant", genre: "FPS" },
  { exe: "Paladins.exe", title: "Paladins", genre: "FPS" },
  { exe: "Quake.exe", title: "Quake (remaster)", genre: "FPS" },
  { exe: "QuakeChampions.exe", title: "Quake Champions", genre: "FPS" },
  { exe: "Diabotical.exe", title: "Diabotical", genre: "FPS" },

  // ─── Battle Royale / Extraction ───
  { exe: "deltaforce.exe", title: "Delta Force", genre: "FPS" },
  { exe: "ringsofpower.exe", title: "Rings of Power", genre: "BR" },
  { exe: "naraka.exe", title: "Naraka Bladepoint", genre: "BR" },
  { exe: "spectreDivide.exe", title: "Spectre Divide", genre: "FPS" },
  { exe: "OffTheGrid.exe", title: "Off The Grid", genre: "FPS" },
  { exe: "ReadyOrNot.exe", title: "Ready or Not", genre: "FPS" },
  { exe: "GroundBranch.exe", title: "Ground Branch", genre: "FPS" },

  // ─── Single-player Shooters / Action ───
  { exe: "Cyberpunk2077.exe", title: "Cyberpunk 2077", genre: "RPG" },
  { exe: "RDR2.exe", title: "Red Dead Redemption 2", genre: "Action" },
  { exe: "GTA5.exe", title: "Grand Theft Auto V", genre: "Action" },
  { exe: "GTA6.exe", title: "Grand Theft Auto VI", genre: "Action" },
  { exe: "FiveM.exe", title: "FiveM", genre: "Action" },
  { exe: "FiveM_GTAProcess.exe", title: "FiveM GTA Process", genre: "Action" },
  { exe: "FiveM_b3323_GTAProcess.exe", title: "FiveM b3323", genre: "Action" },
  { exe: "RedM.exe", title: "RedM", genre: "Action" },
  { exe: "AssassinsCreedShadows.exe", title: "AC Shadows", genre: "Action" },
  { exe: "AssassinsCreedMirage.exe", title: "AC Mirage", genre: "Action" },
  { exe: "AssassinsCreedValhalla.exe", title: "AC Valhalla", genre: "Action" },
  { exe: "GoW.exe", title: "God of War", genre: "Action" },
  { exe: "GoWR.exe", title: "God of War: Ragnarok", genre: "Action" },
  { exe: "HorizonZeroDawn.exe", title: "Horizon Zero Dawn", genre: "Action" },
  { exe: "HorizonForbiddenWest.exe", title: "Horizon Forbidden West", genre: "Action" },
  { exe: "DeathStranding.exe", title: "Death Stranding", genre: "Action" },
  { exe: "DS2.exe", title: "Death Stranding 2", genre: "Action" },
  { exe: "SpiderMan.exe", title: "Spider-Man Remastered", genre: "Action" },
  { exe: "SpiderMan2.exe", title: "Spider-Man 2", genre: "Action" },
  { exe: "TheLastOfUsPartI.exe", title: "TLOU Part I", genre: "Action" },
  { exe: "Indiana.exe", title: "Indiana Jones & The Great Circle", genre: "Action" },
  { exe: "StarWarsOutlaws.exe", title: "Star Wars Outlaws", genre: "Action" },
  { exe: "Jedi.exe", title: "Jedi Survivor", genre: "Action" },
  { exe: "Hogwarts Legacy.exe", title: "Hogwarts Legacy", genre: "RPG" },
  { exe: "FrostpunkII.exe", title: "Frostpunk 2", genre: "Strategy" },

  // ─── RPG / MMO ───
  { exe: "EldenRing.exe", title: "Elden Ring", genre: "RPG" },
  { exe: "EldenRingNightreign.exe", title: "Elden Ring Nightreign", genre: "RPG" },
  { exe: "DarkSoulsIII.exe", title: "Dark Souls III", genre: "RPG" },
  { exe: "sekiro.exe", title: "Sekiro", genre: "RPG" },
  { exe: "BG3.exe", title: "Baldur's Gate 3", genre: "RPG" },
  { exe: "Witcher3.exe", title: "The Witcher 3", genre: "RPG" },
  { exe: "Witcher4.exe", title: "The Witcher 4", genre: "RPG" },
  { exe: "DragonAgeVeilguard.exe", title: "Dragon Age: Veilguard", genre: "RPG" },
  { exe: "Avowed.exe", title: "Avowed", genre: "RPG" },
  { exe: "PathOfExile.exe", title: "Path of Exile", genre: "RPG" },
  { exe: "PathOfExile_x64.exe", title: "PoE (DX12)", genre: "RPG" },
  { exe: "PathOfExile2.exe", title: "Path of Exile 2", genre: "RPG" },
  { exe: "Diablo IV.exe", title: "Diablo IV", genre: "RPG" },
  { exe: "Diablo IV Launcher.exe", title: "Diablo IV Launcher", genre: "RPG" },
  { exe: "Wow.exe", title: "World of Warcraft", genre: "MMO" },
  { exe: "WowClassic.exe", title: "WoW Classic", genre: "MMO" },
  { exe: "ffxiv.exe", title: "Final Fantasy XIV", genre: "MMO" },
  { exe: "ffxiv_dx11.exe", title: "FFXIV (DX11)", genre: "MMO" },
  { exe: "GW2-64.exe", title: "Guild Wars 2", genre: "MMO" },
  { exe: "LostArk.exe", title: "Lost Ark", genre: "MMO" },
  { exe: "Throne.exe", title: "Throne & Liberty", genre: "MMO" },
  { exe: "BlackDesert64.exe", title: "Black Desert", genre: "MMO" },
  { exe: "NewWorld.exe", title: "New World", genre: "MMO" },
  { exe: "NewWorld_x64.exe", title: "New World (x64)", genre: "MMO" },
  { exe: "Once Human.exe", title: "Once Human", genre: "MMO" },

  // ─── MOBA / Card ───
  { exe: "LeagueofLegends.exe", title: "League of Legends", genre: "MOBA" },
  { exe: "League of Legends.exe", title: "LoL Client", genre: "MOBA" },
  { exe: "RiotClientServices.exe", title: "Riot Client", genre: "MOBA" },
  { exe: "dota2.exe", title: "Dota 2", genre: "MOBA" },
  { exe: "Deadlock.exe", title: "Deadlock", genre: "MOBA" },
  { exe: "Smite.exe", title: "Smite", genre: "MOBA" },
  { exe: "Smite2.exe", title: "Smite 2", genre: "MOBA" },
  { exe: "HearthStone.exe", title: "Hearthstone", genre: "Other" },
  { exe: "LegendsOfRuneterra.exe", title: "Legends of Runeterra", genre: "Other" },

  // ─── Survival / Sandbox ───
  { exe: "Minecraft.exe", title: "Minecraft Java", genre: "Sandbox" },
  { exe: "MinecraftLauncher.exe", title: "Minecraft Launcher", genre: "Sandbox" },
  { exe: "javaw.exe", title: "Minecraft (javaw)", genre: "Sandbox" },
  { exe: "Minecraft.Windows.exe", title: "Minecraft Bedrock", genre: "Sandbox" },
  { exe: "RustClient.exe", title: "Rust", genre: "Survival" },
  { exe: "DayZ_x64.exe", title: "DayZ", genre: "Survival" },
  { exe: "ARK.exe", title: "ARK: Survival Evolved", genre: "Survival" },
  { exe: "ArkAscended.exe", title: "ARK: Survival Ascended", genre: "Survival" },
  { exe: "Palworld-Win64-Shipping.exe", title: "Palworld", genre: "Survival" },
  { exe: "ValheimClient.exe", title: "Valheim", genre: "Survival" },
  { exe: "valheim.exe", title: "Valheim (alt)", genre: "Survival" },
  { exe: "7DaysToDie.exe", title: "7 Days to Die", genre: "Survival" },
  { exe: "ProjectZomboid.exe", title: "Project Zomboid", genre: "Survival" },
  { exe: "Terraria.exe", title: "Terraria", genre: "Sandbox" },
  { exe: "TheForest.exe", title: "The Forest", genre: "Survival" },
  { exe: "SonsOfTheForest.exe", title: "Sons of the Forest", genre: "Survival" },
  { exe: "Subnautica.exe", title: "Subnautica", genre: "Survival" },
  { exe: "Subnautica2.exe", title: "Subnautica 2", genre: "Survival" },
  { exe: "Enshrouded.exe", title: "Enshrouded", genre: "Survival" },
  { exe: "Soulmask.exe", title: "Soulmask", genre: "Survival" },
  { exe: "NightingaleClient.exe", title: "Nightingale", genre: "Survival" },
  { exe: "PaxDei.exe", title: "Pax Dei", genre: "Survival" },
  { exe: "Icarus.exe", title: "Icarus", genre: "Survival" },
  { exe: "SCUM.exe", title: "SCUM", genre: "Survival" },
  { exe: "VRising.exe", title: "V Rising", genre: "Survival" },
  { exe: "GreenHell.exe", title: "Green Hell", genre: "Survival" },
  { exe: "stardew.exe", title: "Stardew Valley", genre: "Sim" },
  { exe: "Stardew Valley.exe", title: "Stardew Valley", genre: "Sim" },

  // ─── Roblox / Misc ───
  { exe: "RobloxPlayerBeta.exe", title: "Roblox", genre: "Sandbox" },
  { exe: "RobloxStudioBeta.exe", title: "Roblox Studio", genre: "Sandbox" },
  { exe: "Roblox.exe", title: "Roblox (UWP)", genre: "Sandbox" },

  // ─── Racing / Sim ───
  { exe: "ForzaHorizon5.exe", title: "Forza Horizon 5", genre: "Racing" },
  { exe: "ForzaMotorsport.exe", title: "Forza Motorsport", genre: "Racing" },
  { exe: "F1_24.exe", title: "F1 24", genre: "Racing" },
  { exe: "F1_25.exe", title: "F1 25", genre: "Racing" },
  { exe: "AC2-Win64-Shipping.exe", title: "Assetto Corsa 2", genre: "Racing" },
  { exe: "acs.exe", title: "Assetto Corsa", genre: "Racing" },
  { exe: "acc.exe", title: "Assetto Corsa Competizione", genre: "Racing" },
  { exe: "iRacingSim64DX11.exe", title: "iRacing", genre: "Racing" },
  { exe: "BeamNG.drive.exe", title: "BeamNG.drive", genre: "Racing" },
  { exe: "CarX.exe", title: "CarX Drift Racing", genre: "Racing" },
  { exe: "WreckfestX64.exe", title: "Wreckfest", genre: "Racing" },
  { exe: "TrackmaniaTurbo.exe", title: "Trackmania Turbo", genre: "Racing" },
  { exe: "Trackmania.exe", title: "Trackmania (2020)", genre: "Racing" },
  { exe: "DiRT Rally 2.0.exe", title: "DiRT Rally 2.0", genre: "Racing" },
  { exe: "EAWRC.exe", title: "EA Sports WRC", genre: "Racing" },
  { exe: "rFactor2.exe", title: "rFactor 2", genre: "Racing" },
  { exe: "FlightSimulator.exe", title: "MS Flight Simulator", genre: "Sim" },
  { exe: "FlightSimulator2024.exe", title: "MS Flight Simulator 2024", genre: "Sim" },

  // ─── Sports ───
  { exe: "FIFA25.exe", title: "EA Sports FC 25", genre: "Sports" },
  { exe: "FC25.exe", title: "EA Sports FC 25", genre: "Sports" },
  { exe: "FC26.exe", title: "EA Sports FC 26", genre: "Sports" },
  { exe: "Madden25.exe", title: "Madden 25", genre: "Sports" },
  { exe: "NBA2K25.exe", title: "NBA 2K25", genre: "Sports" },
  { exe: "NBA2K26.exe", title: "NBA 2K26", genre: "Sports" },
  { exe: "PGA2K25.exe", title: "PGA Tour 2K25", genre: "Sports" },

  // ─── Strategy / Sim ───
  { exe: "RocketLeague.exe", title: "Rocket League", genre: "Sports" },
  { exe: "Civ7.exe", title: "Civilization VII", genre: "Strategy" },
  { exe: "CivilizationVII.exe", title: "Civilization VII (alt)", genre: "Strategy" },
  { exe: "ck3.exe", title: "Crusader Kings 3", genre: "Strategy" },
  { exe: "stellaris.exe", title: "Stellaris", genre: "Strategy" },
  { exe: "hoi4.exe", title: "Hearts of Iron 4", genre: "Strategy" },
  { exe: "AOE2DE_s.exe", title: "Age of Empires II DE", genre: "Strategy" },
  { exe: "AOE3DE_s.exe", title: "Age of Empires III DE", genre: "Strategy" },
  { exe: "AOE4.exe", title: "Age of Empires IV", genre: "Strategy" },
  { exe: "StarCraftII.exe", title: "StarCraft II", genre: "Strategy" },
  { exe: "Warhammer3.exe", title: "Total War: Warhammer III", genre: "Strategy" },
  { exe: "Pharaoh.exe", title: "Total War: Pharaoh", genre: "Strategy" },
  { exe: "CitiesSkylines.exe", title: "Cities: Skylines", genre: "Sim" },
  { exe: "CitiesSkylinesII.exe", title: "Cities: Skylines II", genre: "Sim" },
  { exe: "Factorio.exe", title: "Factorio", genre: "Sim" },
  { exe: "Satisfactory.exe", title: "Satisfactory", genre: "Sim" },
  { exe: "FactorySimulator.exe", title: "Factory Sim", genre: "Sim" },
  { exe: "Manor Lords.exe", title: "Manor Lords", genre: "Strategy" },
  { exe: "FrostPunk2.exe", title: "Frostpunk 2", genre: "Strategy" },

  // ─── Fighting ───
  { exe: "Tekken8.exe", title: "Tekken 8", genre: "Fighting" },
  { exe: "SF6.exe", title: "Street Fighter 6", genre: "Fighting" },
  { exe: "MK1.exe", title: "Mortal Kombat 1", genre: "Fighting" },
  { exe: "Granblue.exe", title: "Granblue Fantasy Versus Rising", genre: "Fighting" },
  { exe: "GuiltyGearStrive.exe", title: "Guilty Gear Strive", genre: "Fighting" },
  { exe: "DBFZ.exe", title: "Dragon Ball FighterZ", genre: "Fighting" },

  // ─── Horror / Co-op ───
  { exe: "DeadByDaylight-Win64-Shipping.exe", title: "Dead by Daylight", genre: "Horror" },
  { exe: "Phasmophobia.exe", title: "Phasmophobia", genre: "Horror" },
  { exe: "REVillage.exe", title: "Resident Evil Village", genre: "Horror" },
  { exe: "RE4.exe", title: "Resident Evil 4 Remake", genre: "Horror" },
  { exe: "AlanWake2.exe", title: "Alan Wake 2", genre: "Horror" },
  { exe: "TheTexasChainsawMassacre.exe", title: "Texas Chainsaw", genre: "Horror" },
  { exe: "F13.exe", title: "Friday the 13th", genre: "Horror" },
  { exe: "Lethal Company.exe", title: "Lethal Company", genre: "Horror" },
  { exe: "REPO.exe", title: "R.E.P.O.", genre: "Horror" },
  { exe: "ContentWarning.exe", title: "Content Warning", genre: "Horror" },

  // ─── Roguelike / Indie ───
  { exe: "Hades2.exe", title: "Hades II", genre: "Roguelike" },
  { exe: "Hades.exe", title: "Hades", genre: "Roguelike" },
  { exe: "deadcells.exe", title: "Dead Cells", genre: "Roguelike" },
  { exe: "BindingOfIsaac.exe", title: "Isaac: Repentance", genre: "Roguelike" },
  { exe: "Slay the Spire.exe", title: "Slay the Spire", genre: "Roguelike" },
  { exe: "balatro.exe", title: "Balatro", genre: "Roguelike" },
  { exe: "Risk of Rain 2.exe", title: "Risk of Rain 2", genre: "Roguelike" },
  { exe: "RiskOfRainReturns.exe", title: "Risk of Rain Returns", genre: "Roguelike" },
  { exe: "Vampire Survivors.exe", title: "Vampire Survivors", genre: "Roguelike" },
  { exe: "Brotato.exe", title: "Brotato", genre: "Roguelike" },
  { exe: "Cult.exe", title: "Cult of the Lamb", genre: "Roguelike" },

  // ─── Platformer ───
  { exe: "HollowKnight.exe", title: "Hollow Knight", genre: "Platformer" },
  { exe: "Silksong.exe", title: "Hollow Knight: Silksong", genre: "Platformer" },
  { exe: "Celeste.exe", title: "Celeste", genre: "Platformer" },
  { exe: "Cuphead.exe", title: "Cuphead", genre: "Platformer" },
  { exe: "PrinceofPersia.exe", title: "Prince of Persia", genre: "Platformer" },
  { exe: "Astro.exe", title: "Astro Bot", genre: "Platformer" },

  // ─── Co-op / Misc ───
  { exe: "Helldivers2.exe", title: "Helldivers 2", genre: "FPS" },
  { exe: "deepRockGalactic.exe", title: "Deep Rock Galactic", genre: "FPS" },
  { exe: "WarhammerVT2.exe", title: "Vermintide 2", genre: "Action" },
  { exe: "DarkTide.exe", title: "Warhammer 40K: Darktide", genre: "FPS" },
  { exe: "PayDay3.exe", title: "Payday 3", genre: "FPS" },
  { exe: "REPO_x64.exe", title: "R.E.P.O. (x64)", genre: "Horror" },
  { exe: "ItTakesTwo.exe", title: "It Takes Two", genre: "Platformer" },
  { exe: "Split Fiction.exe", title: "Split Fiction", genre: "Platformer" },
  { exe: "JackBox.exe", title: "Jackbox Party", genre: "Other" },
  { exe: "AmongUs.exe", title: "Among Us", genre: "Other" },
  { exe: "FallGuys_client_game.exe", title: "Fall Guys", genre: "Other" },
  { exe: "MultiVersus.exe", title: "MultiVersus", genre: "Fighting" },
  { exe: "Spore.exe", title: "Spore", genre: "Sim" },

  // ─── 2024–2026 New Releases ───
  { exe: "BlackMythWukong.exe", title: "Black Myth: Wukong", genre: "Action" },
  { exe: "MetaphorReFantazio.exe", title: "Metaphor: ReFantazio", genre: "RPG" },
  { exe: "MonsterHunterWilds.exe", title: "Monster Hunter Wilds", genre: "Action" },
  { exe: "Expedition33.exe", title: "Clair Obscur: Expedition 33", genre: "RPG" },
  { exe: "ARC.exe", title: "ARC Raiders", genre: "FPS" },
  { exe: "Stalker2.exe", title: "S.T.A.L.K.E.R. 2", genre: "FPS" },
  { exe: "Stalker2-Win64-Shipping.exe", title: "S.T.A.L.K.E.R. 2 (UE5)", genre: "FPS" },
  { exe: "KingdomCome2.exe", title: "Kingdom Come: Deliverance II", genre: "RPG" },
  { exe: "Atomfall.exe", title: "Atomfall", genre: "RPG" },
  { exe: "BorderlandsClient.exe", title: "Borderlands 4", genre: "FPS" },
  { exe: "GhostOfYotei.exe", title: "Ghost of Yotei", genre: "Action" },
  { exe: "FableLegends.exe", title: "Fable", genre: "RPG" },
  { exe: "PerfectDark.exe", title: "Perfect Dark", genre: "FPS" },
  { exe: "GearsEDay.exe", title: "Gears of War: E-Day", genre: "FPS" },
  { exe: "Wolfenstein.exe", title: "Wolfenstein", genre: "FPS" },
  { exe: "DoomDarkAges.exe", title: "Doom: The Dark Ages", genre: "FPS" },
  { exe: "DOOMEternal.exe", title: "Doom Eternal", genre: "FPS" },
  { exe: "DOOMx64vk.exe", title: "Doom Eternal (Vulkan)", genre: "FPS" },
  { exe: "Cronos.exe", title: "Cronos: The New Dawn", genre: "Horror" },
  { exe: "SilentHill2.exe", title: "Silent Hill 2 Remake", genre: "Horror" },
  { exe: "RedoutII.exe", title: "Redout II", genre: "Racing" },
];

export const GAME_WHITELIST_COUNT = GAME_WHITELIST.length;
