// Single source of truth: /version.json
//
// Run before `tauri build` (CI does this automatically) so the desktop
// installer carries the same version string the in-app updater compares
// against. Also writes a tiny client/src/generated/version.ts so the
// React bundle can import it without a runtime fetch.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";

const ROOT = resolve(process.cwd());
const versionFile = resolve(ROOT, "version.json");
const tauriConfFile = resolve(ROOT, "src-tauri", "tauri.conf.json");
const generatedFile = resolve(ROOT, "client", "src", "generated", "version.ts");

function main() {
  if (!existsSync(versionFile)) {
    console.error(`sync-version: ${versionFile} not found`);
    process.exit(1);
  }
  const { version, notes } = JSON.parse(readFileSync(versionFile, "utf8")) as {
    version: string;
    notes?: string;
  };
  if (!/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(version)) {
    console.error(`sync-version: invalid semver "${version}"`);
    process.exit(1);
  }

  // 1. Patch src-tauri/tauri.conf.json
  if (existsSync(tauriConfFile)) {
    const conf = JSON.parse(readFileSync(tauriConfFile, "utf8")) as Record<string, unknown>;
    conf.version = version;
    writeFileSync(tauriConfFile, JSON.stringify(conf, null, 2) + "\n");
    console.log(`sync-version: wrote ${version} → src-tauri/tauri.conf.json`);
  }

  // 2. Emit a generated TS module the React bundle can import.
  mkdirSync(dirname(generatedFile), { recursive: true });
  const banner = "// AUTO-GENERATED by scripts/sync-version.ts — do not edit by hand.";
  writeFileSync(
    generatedFile,
    `${banner}\nexport const APP_VERSION = ${JSON.stringify(version)};\nexport const APP_NOTES = ${JSON.stringify(notes ?? "")};\n`,
  );
  console.log(`sync-version: wrote ${version} → client/src/generated/version.ts`);
}

main();
