import { useState, useRef, useCallback } from "react";
import { Cpu, Upload, CheckCircle2, X, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { saveScannedInfo, clearScannedInfo, type ScannedSysInfo } from "@/hooks/use-hardware-info";
import { useToast } from "@/hooks/use-toast";
import { getStoredToken } from "@/lib/pro-status";

function detectGpuVendor(gpuName: string): "nvidia" | "amd" | "intel" {
  const n = (gpuName || "").toLowerCase();
  if (n.includes("nvidia") || n.includes("geforce") || n.includes("rtx") || n.includes("gtx") || n.includes("quadro")) return "nvidia";
  if (n.includes("amd") || n.includes("radeon") || n.includes("rx ") || n.includes("vega") || n.includes("rdna")) return "amd";
  return "intel";
}

function uploadHardwareToServer(parsed: ScannedSysInfo) {
  const token = getStoredToken();
  if (!token) return;
  const gpuVendor = detectGpuVendor(parsed.GPU || "");
  fetch("/api/session/hardware", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      sessionToken: token,
      gpuVendor,
      gpuName: parsed.GPU || "",
      cpuModel: parsed.CPU || "",
      ramGb: parsed.RAM_GB || 16,
      osVersion: "win11",
      isLaptop: false,
    }),
  }).catch(() => {});
}

const PS1_CMD = `$gpu=(Get-WmiObject Win32_VideoController|Where-Object{$_.AdapterRAM -gt 0}|Sort-Object AdapterRAM -Desc|Select-Object -First 1).Name; if(!$gpu){$gpu=(Get-WmiObject Win32_VideoController|Select-Object -First 1).Name}; $cpu=Get-WmiObject Win32_Processor|Select-Object -First 1; $ram=[Math]::Round((Get-WmiObject Win32_ComputerSystem).TotalPhysicalMemory/1GB,0); $path="$env:USERPROFILE\\Desktop\\optigods-sysinfo.json"; if(!(Test-Path "$env:USERPROFILE\\Desktop")){$path="$env:TEMP\\optigods-sysinfo.json"}; @{GPU=$gpu;CPU=$cpu.Name;Cores=$cpu.NumberOfCores;Threads=$cpu.NumberOfLogicalProcessors;RAM_GB=$ram}|ConvertTo-Json|Out-File $path -Encoding utf8 -Force; Write-Host "Done! File saved to: $path" -ForegroundColor Green`;

interface HardwareScanZoneProps {
  onScanned: (info: ScannedSysInfo) => void;
  onCleared: () => void;
  isScanned: boolean;
}

export function HardwareScanZone({ onScanned, onCleared, isScanned }: HardwareScanZoneProps) {
  const [dragging, setDragging] = useState(false);
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  const processFile = useCallback((file: File) => {
    if (!file.name.endsWith(".json")) {
      toast({ title: "Wrong file", description: "Drop the optigods-sysinfo.json file generated by the scan command.", variant: "destructive" });
      return;
    }
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const parsed = JSON.parse(e.target?.result as string) as ScannedSysInfo;
        if (!parsed.GPU && !parsed.CPU && !parsed.RAM_GB) throw new Error("empty");
        saveScannedInfo(parsed);
        uploadHardwareToServer(parsed);
        onScanned(parsed);
        toast({ title: "Hardware scan loaded!", description: `GPU: ${parsed.GPU || "?"} · RAM: ${parsed.RAM_GB ?? "?"}GB · CPU: ${parsed.CPU || "?"}` });
      } catch {
        toast({ title: "Invalid scan file", description: "Could not parse the JSON. Re-run the scan command and try again.", variant: "destructive" });
      }
    };
    reader.readAsText(file);
  }, [onScanned, toast]);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragging(false);
    const file = e.dataTransfer.files[0];
    if (file) processFile(file);
  }, [processFile]);

  const handleFileChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) processFile(file);
    e.target.value = "";
  }, [processFile]);

  const copyCmd = () => {
    navigator.clipboard.writeText(PS1_CMD).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleClear = () => {
    clearScannedInfo();
    onCleared();
    toast({ title: "Hardware scan cleared", description: "Detection will fall back to browser APIs." });
  };

  if (isScanned) {
    return (
      <button
        onClick={handleClear}
        data-testid="button-hardware-clear-scan"
        className="flex items-center gap-1.5 text-xs text-green-400 hover:text-red-400 transition-colors"
        title="Clear hardware scan data"
      >
        <CheckCircle2 className="w-3.5 h-3.5" />
        <span>Scanned</span>
        <X className="w-3 h-3 opacity-60" />
      </button>
    );
  }

  return (
    <div className="mt-3">
      {!expanded ? (
        <button
          onClick={() => setExpanded(true)}
          data-testid="button-hardware-scan-open"
          className="flex items-center gap-1.5 text-xs text-zinc-500 hover:text-red-400 transition-colors border border-dashed border-zinc-700 hover:border-red-500/50 rounded-lg px-3 py-2 w-full"
        >
          <Cpu className="w-3.5 h-3.5" />
          <span>GPU / RAM not showing? Run hardware scan</span>
        </button>
      ) : (
        <div className="border border-zinc-700/60 rounded-xl bg-black/40 p-4 space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-zinc-300 uppercase tracking-wider">Hardware Scan</span>
            <button onClick={() => setExpanded(false)} className="text-zinc-600 hover:text-zinc-400 transition-colors">
              <X className="w-3.5 h-3.5" />
            </button>
          </div>

          <div className="text-xs text-zinc-400 leading-relaxed">
            Open <span className="text-white font-mono">PowerShell as Admin</span>, paste and run this command, then drag the file it creates onto the box below:
          </div>

          <div className="relative">
            <pre className="text-[9px] leading-relaxed bg-zinc-900 border border-zinc-700 rounded-lg p-3 overflow-x-auto overflow-y-auto max-h-32 text-green-400 whitespace-pre font-mono">
              {PS1_CMD}
            </pre>
            <button
              onClick={copyCmd}
              data-testid="button-hardware-scan-copy"
              className="absolute top-2 right-2 p-1.5 rounded bg-zinc-800 hover:bg-zinc-700 text-zinc-400 hover:text-white transition-colors"
              title="Copy command"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
            </button>
          </div>

          <div
            onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
            onDragLeave={() => setDragging(false)}
            onDrop={handleDrop}
            onClick={() => fileRef.current?.click()}
            data-testid="zone-hardware-scan-drop"
            className={cn(
              "border-2 border-dashed rounded-xl p-5 text-center cursor-pointer transition-all",
              dragging
                ? "border-red-500 bg-red-500/10 text-red-400"
                : "border-zinc-700 hover:border-zinc-500 text-zinc-500 hover:text-zinc-400"
            )}
          >
            <Upload className="w-5 h-5 mx-auto mb-2 opacity-60" />
            <div className="text-xs">
              {dragging ? "Drop optigods-sysinfo.json here" : "Drag optigods-sysinfo.json here, or click to browse"}
            </div>
          </div>
          <input ref={fileRef} type="file" accept=".json" className="hidden" onChange={handleFileChange} />
        </div>
      )}
    </div>
  );
}
