import { create } from 'zustand';
import { persist } from 'zustand/middleware';

interface OptimizationState {
  tweaks: Record<string, boolean>;
  nvidiaPreset: string;
  systemRamGB: number | null;
  /** Task #39 — per-tweak applied timestamp (ms epoch). Used to render the inline Undo button. */
  appliedAt: Record<string, number>;
  setSystemRamGB: (gb: number) => void;
  toggleTweak: (key: string) => void;
  setTweak: (key: string, value: boolean) => void;
  setNvidiaPreset: (preset: string) => void;
  setAllTweaks: (tweaks: Record<string, boolean>) => void;
  markApplied: (ids: string[]) => void;
  clearApplied: (id: string) => void;
  clearAllApplied: () => void;
  reset: () => void;
}

export const DEFAULT_TWEAKS: Record<string, boolean> = {
  // Registry - CPU Scheduling
  Win32PrioritySeparation: false,
  DisableHungAppDetection: false,
  DisablePagefileEncryption: false,
  SetTimerResolution: false,
  SetResponsiveness: false,
  EnableMSIMode: false,
  GameModeTweaks: false,
  // Registry - Network
  NetworkThrottling: false,
  OptimizeTCP: false,
  DisableNagle: false,
  InputLagTCP: false,
  EnableTCPAutoTuning: false,
  DisablePowerThrottling: false,
  SetDNSPriority: false,
  DisableNDU: false,
  DisableIPv6: false,
  // Registry - Memory
  DisablePrefetch: false,
  ClearPagefileOnShutdown: false,
  DisableMemoryCompression: false,
  OptimizeRAMUsage: false,
  // Registry - Visual/Gaming
  DisableAnimations: false,
  DisableTelemetry: false,
  DisableXboxGameBar: false,
  DisableGameDVR: false,
  SysVisualBestPerf: false,
  SysHibernateOff: false,
  SysHypervisorOff: false,
  EnableHAGS: false,
  DisablePointerPrecision: false,
  DisableFastStartup: false,
  DisableWindowsError: false,
  DisableAutoUpdate: false,
  DisableDefender: false,
  // Registry - Power
  SetHighPerformancePlan: false,
  DisableUSBSuspend: false,
  DisableCoreParking: false,
  DisablePowerThrottlingAdv: false,
  DisableDynamicTick: false,
  // Registry - Advanced Network
  NetDNSCloudflare: false,
  NetDNSGoogle: false,
  NetDisableQoS: false,
  NetInterruptModeration: false,
  NetRSSQueues: false,
  NetAdapterPowerSave: false,
  NetTCPChimneyOffload: false,
  // Registry - Windows 11 Gaming
  Win11DisableVBS: false,
  Win11DisableHVCI: false,
  Win11ParkingCoreOverride: false,
  Win11ProcessorIdleMin: false,
  // Registry - Advanced Process
  ProcNUMAAware: false,
  ProcAffinityFPS: false,
  ProcMMCSSGaming: false,
  ProcGPUSchedulerHigh: false,
  // FiveM
  FiveMCacheClear: false,
  FiveMHighPriority: false,
  FiveMDisablePhysX: false,
  FiveMExtendedMemory: false,
  FiveMNetworkBuffer: false,
  FiveMDisableVSync: false,
  FiveMStreamDistance: false,
  FiveMDisableFullscreen: false,
  FiveMDisableDWM: false,
  FiveMAffinityMask: false,
  FiveMIOPriority: false,
  FiveMDisableP2P: false,
  FiveMDNSOverride: false,
  FiveMQueueFix: false,
  FiveMWorkingSet: false,
  FiveMStreamPool: false,
  FiveMDisableNvidiaTelemetry: false,
  FiveMMenuFpsUncap: false,
  FiveMDisableMemCompression: false,
  FiveMDisableLSO: false,
  FiveMEnableRSS: false,
  FiveMReduceNPCDensity: false,
  FiveMReduceShadowQuality: false,
  FiveMCommandLineTweaks: false,
  FiveMFullPerfStack: false,
  FiveMGTAProcessPerfOptions: false,
  FiveMGameModeAdd: false,
  FiveMRenderingBoost: false,
  FiveMGPUPriorityStack: false,
  FiveM1060VRAMFlag: false,
  FiveM1060DisableHAGS: false,
  FiveM1060AnselDisable: false,
  FiveM5600CoreAffinity: false,
  FiveM5600PowerPlan: false,
  // FiveM: GTX 1650 SUPER specific
  FiveM1650DisableHAGS: false,
  FiveM1650VRAMBudget: false,
  FiveM1650DisableAnsel: false,
  FiveM1650LowLatencyMode: false,
  // FiveM: Ryzen 5 3500 specific
  FiveM3500CoreAffinity: false,
  FiveM3500PerfPlan: false,
  // FiveM: CitizenFX config + commandline
  FiveMCitizenDisableMedia: false,
  FiveMSteamChildOff: false,
  FiveMCommandlineMax: false,
  FiveMSteamOverlayOff: false,
  FiveMMMCSSAudio: false,
  FiveMDisableMPO: false,
  FiveMFixNvidiaOverlay: false,
  FiveMFixProductId: false,
  // Process Lasso
  ProcessLassoProBalance: false,
  ProcessLassoSmartTrim: false,
  ProcessLassoRestrain: false,
  ProcessLassoAffinityGaming: false,
  ProcessLassoInstanceBalancer: false,
  ProcessTrimWorkingSet: false,
  ProcessDisableWindowsErrorReporting: false,
  ProcessAutoKillHung: false,
  // Debloat - Apps (Win10)
  DebloatCortana: false,
  DebloatOneDrive: false,
  DebloatXboxApp: false,
  DebloatXboxGameBar: false,
  DebloatXboxIdentity: false,
  DebloatBing: false,
  DebloatWeather: false,
  DebloatNews: false,
  DebloatMaps: false,
  DebloatSolitaire: false,
  DebloatMixedReality: false,
  DebloatSkype: false,
  DebloatZune: false,
  DebloatGrooveMusic: false,
  DebloatOfficeHub: false,
  DebloatFeedback: false,
  DebloatGetHelp: false,
  DebloatMSPaint3D: false,
  DebloatWindowsCamera: false,
  DebloatYourPhone: false,
  DebloatClipchamp: false,
  DebloatPowerAutomate: false,
  DebloatQuickAssist: false,
  DebloatTeamsConsumer: false,
  DebloatAlarmsAndClock: false,
  // Debloat - Services
  ServiceDiagTrack: false,
  ServiceWSearch: false,
  ServiceSysMain: false,
  ServiceRemoteReg: false,
  ServiceWMPNetworkSvc: false,
  ServiceFax: false,
  ServiceRetailDemo: false,
  ServiceTabletInput: false,
  ServiceMapsBroker: false,
  ServiceWerSvc: false,
  ServiceDPS: false,
  ServicePrintSpooler: false,
  ServiceDusmSvc: false,
  ServiceTrkWks: false,
  ServiceLltdsvc: false,
  ServiceFDHost: false,
  ServiceWbioSrvc: false,
  ServicePcaSvc: false,
  ServiceAeLookupSvc: false,
  // Debloat - Privacy
  PrivacyTelemetry: false,
  PrivacyActivityHistory: false,
  PrivacyLocationTracking: false,
  PrivacyAdvertisingID: false,
  PrivacyDiagFeedback: false,
  // Win11 Debloat
  Win11TeamsChat: false,
  Win11Widgets: false,
  Win11Copilot: false,
  Win11StartRecommended: false,
  Win11EdgeSidebar: false,
  Win11ChatIcon: false,
  Win11OneDriveBackup: false,
  Win11AdsInStart: false,
  Win11DeviceEncryption: false,
  Win11Snap: false,
  Win11TPMAlert: false,
  Win11BingSearch: false,
  Win11NotepadAI: false,
  Win11AutoHDR: false,
  // AMD Specific
  AmdDisableULPS: false,
  AmdDisableChill: false,
  AmdDisablePowerEfficiency: false,
  AmdDisableVSR: false,
  AmdMaxClockState: false,
  AmdDisableTelemetry: false,
  AmdDisableCrashDefender: false,
  AmdOptimizeLatency: false,
  AmdShaderCache: false,
  AmdDisableFreeSyncCompetitive: false,
  AmdDisableVariBright: false,
  AmdForcePerformancePowerPlan: false,
  AmdImageSharpening: false,
  AmdAntiLag: false,
  AmdDisableStartupApps: false,
  AmdTDRTweak: false,
  AmdSmartAccessMemory: false,
  AmdAntiLagPlus: false,
  AmdFluidMotionFrames: false,
  AmdResizableBAR: false,
  AmdRadeonBoost: false,
  AmdEnhancedSync: false,
  // NVIDIA Specific
  NvidiaDisableTelemetry: false,
  NvidiaMaxPerfMode: false,
  NvidiaPreRenderedFrames: false,
  NvidiaShaderCache: false,
  NvidiaOptimizeLatency: false,
  NvidiaDisableOverlay: false,
  NvidiaLowLatency: false,
  NvidiaThreadedOpt: false,
  NvidiaForceVSyncOff: false,
  NvidiaPowerMizer: false,
  NvidiaAnisoFiltering: false,
  NvidiaTripleBufferOff: false,
  NvidiaReflexEnable: false,
  NvidiaGSyncOptimize: false,
  NvidiaOpenGLOpt: false,
  NvidiaVRAMMax: false,
  NvShaderDiskCache: false,
  NvTextureFilterPerf: false,
  NvFXAADriverOff: false,
  NvidiaCUDAPriority: false,
  NvidiaShaderCacheUnlimited: false,
  NvidiaFrameBufferOpt: false,
  NvidiaDisableAnsel: false,
  NvidiaDisableContainerLS: false,
  NvidiaDisableShadowPlay: false,
  // Memory
  MemFixedPagefile: false,
  MemDisablePagefile: false,
  MemClearPagefileShutdown: false,
  MemMovePagefileFast: false,
  MemDisableCompression: false,
  MemDisableSuperfetch: false,
  MemTrimStandbyList: false,
  MemDisableKernelPaging: false,
  MemSystemCacheBoost: false,
  MemTrimOnMinimize: false,
  MemLargePageSupport: false,
  MemSetWorkingSetSize: false,
  MemDisableHeapTermination: false,
  MemGPUOptimize: false,
  MemDisableGPUPagefile: false,
  EnableLargeSystemCache: false,
  MemGPUSchedulerTweak: false,
  // Game Detection
  game_valorant: false,
  game_cs2: false,
  game_apex: false,
  game_warzone: false,
  game_lol: false,
  game_overwatch: false,
  game_siege: false,
  game_rust: false,
  game_minecraft: false,
  game_roblox: false,
  game_tarkov: false,
  game_pubg: false,
  game_dbd: false,
  game_dota2: false,
  game_warframe: false,
  game_forza: false,
  game_readyornot: false,
  game_phasmo: false,
  game_battlefield: false,
  game_gta5: false,
  game_fivem: false,
  game_rocketleague: false,
  game_arcraiders: false,
  game_marvelrivals: false,
  // Fortnite
  FortniteHighPriority: false,
  FortniteUncapLobbyFPS: false,
  FortniteUncapGameFPS: false,
  FortniteDisableVSync: false,
  FortniteEngineStreaming: false,
  FortniteDisableMotionBlur: false,
  FortniteNetworkBuffer: false,
  FortniteLowShadows: false,
  FortniteDisableLumen: false,
  FortniteForceDirectX12: false,
  FortniteDisableRecording: false,
  FortniteAffinityPhysical: false,
  FortniteInputLatency: false,
  FortniteGameMode: false,
  FortniteDisableThrottling: false,
  // WinUtil / ChrisTitus / OO ShutUp
  WinTitusConsumerFeatures: false,
  WinTitusHibernation: false,
  WinTitusPosh7Telemetry: false,
  WinTitusWPBT: false,
  WinTitusDiskCleanup: false,
  WinTitusServicesManual: false,
  WinTitusAdobeBlock: false,
  WinTitusRazerBlock: false,
  WinTitusBgApps: false,
  WinTitusFullscreenOpt: false,
  WinTitusNotifTray: false,
  WinTitusStorageSense: false,
  WinTitusTeredo: false,
  WinTitusEdgeDebloat: false,
  WinTitusIPv4Prefer: false,
  WinTitusEdgeRemove: false,
  WinTitusXboxComponents: false,
  WinTitusClassicMenu: false,
  WinTitusDisplayPerf: false,
  WinTitusShowExtensions: false,
  WinTitusShowHidden: false,
  OOShutupPrivacy: false,
  // Discord Optimizer
  DiscordLowPriority: false,
  DiscordDisableHWAccel: false,
  DiscordClearCache: false,
  DiscordDisableUpdateCheck: false,
  DiscordReduceGPUPriority: false,
  DiscordOptimizeCodec: false,
  DiscordDisableCrashHandler: false,
  DiscordDisableAnimations: false,
  DiscordDisableOverlay: false,
  DiscordDisableClips: false,
  DiscordDisableVAD: false,
  DiscordLowerVoiceQuality: false,
  DiscordDisableStreaming: false,
  // Startup Apps
  su_discord: false,
  su_spotify: false,
  su_steam: false,
  su_onedrive: false,
  su_teams: false,
  su_skype: false,
  su_zoom: false,
  su_rtss: false,
  su_msiab: false,
  su_nvidia: false,
  su_ccleaner: false,
  su_realtek: false,
  su_logitech: false,
  su_corsair: false,
  su_amdradeon: false,
  // Integrated Graphics (AMD Vega / Intel UHD)
  IGpu_DisableULPS: false,
  IGpu_DisableDeepSleep: false,
  IGpu_DisableVariBright: false,
  IGpu_ForcePerformancePower: false,
  IGpu_DisableTransparency: false,
  IGpu_DisableAnimations: false,
  IGpu_DisableHDR: false,
  IGpu_DisableNightLight: false,
  IGpu_DisableSysMain: false,
  IGpu_GameModeOn: false,
  IGpu_UltimatePerformancePlan: false,
  IGpu_MaxProcessorState: false,
  IGpu_DisableFullscreenOpt: false,
  IGpu_DisableXboxGameBar: false,
  IGpu_AmdAntiLag: false,
  IGpu_SharedMemoryHint: false,
  IGpu_DisableDWMColorSpace: false,
  IGpu_SetTimerResolution: false,
  IGpu_CloseBrowserGPU: false,
  IGpu_DisableCoreParking: false,
  IGpu_Intel_MaxFreq: false,
  IGpu_Intel_DisableFreqScaling: false,
  IGpu_Intel_TDR: false,
  IGpu_Intel_PanelFitter: false,
  IGpu_Intel_QSVOff: false,
  IGpu_DisableHAGSForIGpu: false,
  IGpu_NetworkThrottling: false,
  IGpu_DisableMPO: false,
  IGpu_AmdTdrLevel: false,
  IGpu_AmdDisableHDCP: false,
  IGpu_AmdVegaAudioOff: false,
  // Laptop Optimizer
  Lap_UltimatePerformance: false,
  Lap_DisableCoreParking: false,
  Lap_DisableThrottleStates: false,
  Lap_MaxProcessorStateAC: false,
  Lap_DisableTurboOnBattery: false,
  Lap_DisableAdaptiveBrightness: false,
  Lap_DisableHibernate: false,
  Lap_AMD_DisableULPS: false,
  Lap_AMD_DisableVariBright: false,
  Lap_AMD_DisableDeepSleep: false,
  Lap_AMD_DisableDynamicVoltage: false,
  Lap_AMD_ForcePerformance: false,
  Lap_NVIDIA_MaxPerformance: false,
  Lap_NVIDIA_DisableVsync: false,
  Lap_NVIDIA_LowLatency: false,
  Lap_NVIDIA_ThreadedOpt: false,
  Lap_NVIDIA_DisableMaxQThrottle: false,
  Lap_Intel_DisableTurboLimits: false,
  Lap_Intel_DisableSpeedShift: false,
  Lap_Intel_DisableECores: false,
  Lap_Net_DisableNagle: false,
  Lap_Net_DisableThrottle: false,
  Lap_Net_DisableAutoTuning: false,
  Lap_Net_OptimizeDNS: false,
  Lap_Net_DisableUSBSelSuspend: false,
  Lap_Net_WiFiPerfMode: false,
  Lap_TimerResolution: false,
  Lap_DisablePowerThrottling: false,
  Lap_DisableXboxGameBar: false,
  Lap_DisableFullscreenOpt: false,
  Lap_MMCSS_Games: false,
  Lap_DisableMPO: false,
  Lap_VisualPerformance: false,
  Lap_DisableHAGS: false,
  Lap_USBPowerSave: false,
  Lap_WifiPerfMode: false,
  // Processes Reduction — services to Manual
  ProcSvc_DiagTrack: false,
  ProcSvc_WerSvc: false,
  ProcSvc_DPS: false,
  ProcSvc_DusmSvc: false,
  ProcSvc_DoSvc: false,
  ProcSvc_XblAuth: false,
  ProcSvc_XblGame: false,
  ProcSvc_XboxNet: false,
  ProcSvc_XboxGip: false,
  ProcSvc_SSDP: false,
  ProcSvc_FDServices: false,
  ProcSvc_Lltdsvc: false,
  ProcSvc_SharedAccess: false,
  ProcSvc_WinRM: false,
  ProcSvc_WbioSrvc: false,
  ProcSvc_TabletInput: false,
  ProcSvc_BthServ: false,
  ProcSvc_Fax: false,
  ProcSvc_MapsBroker: false,
  ProcSvc_lfsvc: false,
  ProcSvc_PhoneSvc: false,
  ProcSvc_RetailDemo: false,
  ProcSvc_WMPNet: false,
  ProcSvc_TrkWks: false,
  ProcSvc_W32Time: false,
  ProcSvc_BITS: false,
  ProcSvc_WSearch: false,
  ProcSvc_SysMain: false,
  ProcSvc_RemoteReg: false,
  ProcSvc_ApplyAll: false,
  // Cloud & Notification Services
  ProcSvc_OneSyncSvc: false,
  ProcSvc_CDPSvc: false,
  ProcSvc_WpnService: false,
  ProcSvc_cbdhsvc: false,
  ProcSvc_dmwappushsvc: false,
  ProcSvc_PushToInstall: false,
  // IoT, Remote & Legacy Network
  ProcSvc_AJRouter: false,
  ProcSvc_SharedRealitySvc: false,
  ProcSvc_icssvc: false,
  ProcSvc_WFDSConMgr: false,
  ProcSvc_p2pimsvc: false,
  // Enterprise & System Misc
  ProcSvc_EapHost: false,
  ProcSvc_seclogon: false,
  ProcSvc_SCardSvr: false,
  ProcSvc_AppReadiness: false,
  ProcSvc_PcaSvc: false,
  ProcSvc_PrintNotify: false,
  // NVIDIA GPU Thermal Management
  NvidiaDisableHDMIAudio: false,
  NvidiaRTXVideoOff: false,
  NvidiaGpuBgOptimize: false,
  // AMD CPU Performance (Zen 2 / Zen 3 — Ryzen 5 3500, 7 3700X, etc.)
  AmdCpuCoalescingOff: false,
  AmdCpuPowerPinMax: false,
  AmdCpuCStatePolicy: false,
  AmdCpuCapabilities: false,
  AmdCpuSchedulerHint: false,
  // AMD GPU Thermal Management
  AmdDisableHDMIAudio: false,
  AmdDisableReLive: false,
  // Registry: Advanced Kernel Tweaks
  RegistryNTFSOptimize: false,
  RegistryIOPageLock: false,
  RegistryDPCLatency: false,
  RegistryLargePageHeap: false,
  // Additional Startup Apps
  su_ea_app: false,
  su_epic: false,
  su_ubisoft: false,
  su_battlenet: false,
  su_razer: false,
  su_chrome: false,
  su_firefox: false,
  su_edge_startup: false,
  su_obs: false,
  // V2 NEW (Task #38) — Network / Security / Anti-cheat / Input / RTX 50 / RX 9000 / Zen 5 / Arrow Lake / DPC tool
  NetMTUAutotune: false,
  NetTCPAutotuneAggressive: false,
  NetRSSTuning: false,
  NetDNSQuad9: false,
  NetDisableLargeSendOffload: false,
  SecDetectVBSStatus: false,
  SecDisableMemoryIntegrity: false,
  SecDisableCredentialGuard: false,
  SecDisableMitigationsForGames: false,
  ACDetectVanguard: false,
  ACDetectEAC: false,
  ACDetectBattlEyeFACEIT: false,
  InputUSBPollingCheck: false,
  InputRawAccelBanner: false,
  InputMousePollHzVerify: false,
  RTX50DLSS4FrameGen: false,
  RTX50Reflex2: false,
  RTX50PowerModeLock: false,
  RTX50ShaderCacheBump: false,
  RTX50BlackwellDriverOpt: false,
  RTX50ComputeSm120: false,
  RTX50NVCPSettings: false,
  RTX50NvidiaAppTelemetryOff: false,
  RX9000RDNA4AFMF2: false,
  RX9000HyprRX: false,
  RX9000AntiLag2NextGen: false,
  RX9000PowerSlider: false,
  RX9000Adrenalin2025TelemetryOff: false,
  RX9000SAMVerify: false,
  Zen5CurveOptimizer: false,
  Zen5PBOScalarLock: false,
  Zen5SMTSchedulerHint: false,
  Zen5AGESACStatePolicy: false,
  Zen5X3DCachePin: false,
  ArrowAPOOptIn: false,
  ArrowThreadDirectorHint: false,
  ArrowEcoreParkPolicy: false,
  ArrowLunarLakePowerPlan: false,
  ArrowITDTelemetryOff: false,
  ToolDPCLatencyCheck: false,
};

export const useOptimizationStore = create<OptimizationState>()(
  persist(
    (set) => ({
      tweaks: { ...DEFAULT_TWEAKS },
      nvidiaPreset: '',
      systemRamGB: null,
      appliedAt: {},

      setSystemRamGB: (gb) => set({ systemRamGB: gb }),

      toggleTweak: (key) => set((state) => ({
        tweaks: { ...state.tweaks, [key]: !state.tweaks[key] }
      })),

      setTweak: (key, value) => set((state) => ({
        tweaks: { ...state.tweaks, [key]: value }
      })),

      setNvidiaPreset: (preset) => set({ nvidiaPreset: preset }),

      setAllTweaks: (tweaks) => set({ tweaks }),

      markApplied: (ids) => set((state) => {
        const now = Date.now();
        const next = { ...state.appliedAt };
        for (const id of ids) next[id] = now;
        return { appliedAt: next };
      }),

      clearApplied: (id) => set((state) => {
        if (!(id in state.appliedAt)) return state;
        const next = { ...state.appliedAt };
        delete next[id];
        return { appliedAt: next };
      }),

      clearAllApplied: () => set({ appliedAt: {} }),

      reset: () => set({ tweaks: { ...DEFAULT_TWEAKS }, nvidiaPreset: '', appliedAt: {} }),
    }),
    {
      name: 'optigods-tweaks-v1',
      partialize: (state: OptimizationState) => ({ tweaks: state.tweaks, nvidiaPreset: state.nvidiaPreset, appliedAt: state.appliedAt }),
    }
  )
);
