import { create } from 'zustand';
import { persist } from 'zustand/middleware';

interface OptimizationState {
  tweaks: Record<string, boolean>;
  nvidiaPreset: string;
  systemRamGB: number | null;
  setSystemRamGB: (gb: number) => void;
  toggleTweak: (key: string) => void;
  setTweak: (key: string, value: boolean) => void;
  setNvidiaPreset: (preset: string) => void;
  setAllTweaks: (tweaks: Record<string, boolean>) => void;
  reset: () => void;
}

const DEFAULT_TWEAKS: Record<string, boolean> = {
  // Registry - CPU Scheduling
  Win32PrioritySeparation: false,
  DisableHungAppDetection: false,
  EnableLargeSystemCache: false,
  DisablePagefileEncryption: false,
  SetTimerResolution: false,
  SetResponsiveness: false,
  EnableMSIMode: false,
  GameModeTweaks: false,
  // Registry - Network
  NetworkThrottling: false,
  OptimizeTCP: false,
  DisableNagle: false,
  InputLagTCP: false,
  EnableTCPAutoTuning: false,
  DisablePowerThrottling: false,
  SetDNSPriority: false,
  DisableNDU: false,
  DisableIPv6: false,
  // Registry - Memory
  DisablePrefetch: false,
  ClearPagefileOnShutdown: false,
  DisableMemoryCompression: false,
  OptimizeRAMUsage: false,
  // Registry - Visual/Gaming
  DisableAnimations: false,
  DisableTelemetry: false,
  DisableXboxGameBar: false,
  DisableGameDVR: false,
  EnableHAGS: false,
  DisablePointerPrecision: false,
  DisableFastStartup: false,
  DisableWindowsError: false,
  DisableAutoUpdate: false,
  DisableDefender: false,
  // Registry - Power
  SetHighPerformancePlan: false,
  DisableUSBSuspend: false,
  DisableCoreParking: false,
  DisablePowerThrottlingAdv: false,
  DisableDynamicTick: false,
  // FiveM
  FiveMCacheClear: false,
  FiveMHighPriority: false,
  FiveMDisablePhysX: false,
  FiveMExtendedMemory: false,
  FiveMNetworkBuffer: false,
  FiveMDisableVSync: false,
  FiveMStreamDistance: false,
  FiveMDisableFullscreen: false,
  FiveMDisableDWM: false,
  FiveMAffinityMask: false,
  FiveMIOPriority: false,
  FiveMDisableP2P: false,
  FiveMDNSOverride: false,
  FiveMQueueFix: false,
  FiveMWorkingSet: false,
  FiveMStreamPool: false,
  FiveMDisableNvidiaTelemetry: false,
  FiveMFullPerfStack: false,
  FiveMGTAProcessPerfOptions: false,
  FiveMGameModeAdd: false,
  FiveMRenderingBoost: false,
  FiveMGPUPriorityStack: false,
  // Process Lasso
  ProcessLassoProBalance: false,
  ProcessLassoSmartTrim: false,
  ProcessLassoRestrain: false,
  ProcessLassoAffinityGaming: false,
  ProcessLassoInstanceBalancer: false,
  ProcessTrimWorkingSet: false,
  ProcessDisableWindowsErrorReporting: false,
  ProcessAutoKillHung: false,
  // Debloat - Apps (Win10)
  DebloatCortana: false,
  DebloatOneDrive: false,
  DebloatXboxApp: false,
  DebloatXboxGameBar: false,
  DebloatXboxIdentity: false,
  DebloatBing: false,
  DebloatWeather: false,
  DebloatNews: false,
  DebloatMaps: false,
  DebloatSolitaire: false,
  DebloatMixedReality: false,
  DebloatSkype: false,
  DebloatZune: false,
  DebloatGrooveMusic: false,
  DebloatOfficeHub: false,
  DebloatFeedback: false,
  DebloatGetHelp: false,
  DebloatMSPaint3D: false,
  DebloatWindowsCamera: false,
  DebloatYourPhone: false,
  DebloatClipchamp: false,
  DebloatPowerAutomate: false,
  DebloatQuickAssist: false,
  DebloatTeamsConsumer: false,
  DebloatAlarmsAndClock: false,
  // Debloat - Services
  ServiceDiagTrack: false,
  ServiceWSearch: false,
  ServiceSysMain: false,
  ServiceRemoteReg: false,
  ServiceWMPNetworkSvc: false,
  ServiceFax: false,
  ServiceRetailDemo: false,
  ServiceTabletInput: false,
  ServiceMapsBroker: false,
  // Debloat - Privacy
  PrivacyTelemetry: false,
  PrivacyActivityHistory: false,
  PrivacyLocationTracking: false,
  PrivacyAdvertisingID: false,
  PrivacyDiagFeedback: false,
  // Win11 Debloat
  Win11TeamsChat: false,
  Win11Widgets: false,
  Win11Copilot: false,
  Win11StartRecommended: false,
  Win11EdgeSidebar: false,
  Win11ChatIcon: false,
  Win11OneDriveBackup: false,
  Win11AdsInStart: false,
  Win11DeviceEncryption: false,
  Win11Snap: false,
  Win11TPMAlert: false,
  Win11BingSearch: false,
  Win11NotepadAI: false,
  Win11AutoHDR: false,
  // AMD Specific
  AmdDisableULPS: false,
  AmdDisableChill: false,
  AmdDisablePowerEfficiency: false,
  AmdDisableVSR: false,
  AmdMaxClockState: false,
  AmdDisableTelemetry: false,
  AmdDisableCrashDefender: false,
  AmdOptimizeLatency: false,
  AmdShaderCache: false,
  AmdDisableFreeSyncCompetitive: false,
  AmdDisableVariBright: false,
  AmdForcePerformancePowerPlan: false,
  AmdImageSharpening: false,
  AmdAntiLag: false,
  AmdDisableStartupApps: false,
  AmdTDRTweak: false,
  AmdSmartAccessMemory: false,
  AmdAntiLagPlus: false,
  AmdFluidMotionFrames: false,
  // NVIDIA Specific
  NvidiaDisableTelemetry: false,
  NvidiaMaxPerfMode: false,
  NvidiaPreRenderedFrames: false,
  NvidiaShaderCache: false,
  NvidiaOptimizeLatency: false,
  NvidiaDisableOverlay: false,
  NvidiaLowLatency: false,
  NvidiaThreadedOpt: false,
  NvidiaForceVSyncOff: false,
  NvidiaPowerMizer: false,
  NvidiaAnisoFiltering: false,
  NvidiaTripleBufferOff: false,
  NvidiaReflexEnable: false,
  NvidiaGSyncOptimize: false,
  NvidiaOpenGLOpt: false,
  NvidiaVRAMMax: false,
  // Memory
  MemFixedPagefile: false,
  MemDisablePagefile: false,
  MemClearPagefileShutdown: false,
  MemMovePagefileFast: false,
  MemDisableCompression: false,
  MemDisableSuperfetch: false,
  MemTrimStandbyList: false,
  MemDisableKernelPaging: false,
  MemSystemCacheBoost: false,
  MemTrimOnMinimize: false,
  MemLargePageSupport: false,
  MemSetWorkingSetSize: false,
  MemDisableHeapTermination: false,
  MemGPUOptimize: false,
  MemDisableGPUPagefile: false,
  MemGPUSchedulerTweak: false,
  // Game Detection
  game_valorant: false,
  game_cs2: false,
  game_apex: false,
  game_warzone: false,
  game_lol: false,
  game_overwatch: false,
  game_siege: false,
  game_rust: false,
  game_minecraft: false,
  game_roblox: false,
  game_tarkov: false,
  game_pubg: false,
  game_dbd: false,
  game_dota2: false,
  game_warframe: false,
  game_forza: false,
  game_readyornot: false,
  game_phasmo: false,
  game_battlefield: false,
  // Fortnite
  FortniteHighPriority: false,
  FortniteUncapLobbyFPS: false,
  FortniteUncapGameFPS: false,
  FortniteDisableVSync: false,
  FortniteEngineStreaming: false,
  FortniteDisableMotionBlur: false,
  FortniteNetworkBuffer: false,
  FortniteLowShadows: false,
  FortniteDisableLumen: false,
  FortniteForceDirectX12: false,
  FortniteDisableRecording: false,
  FortniteAffinityPhysical: false,
  FortniteInputLatency: false,
  FortniteGameMode: false,
  FortniteDisableThrottling: false,
  // WinUtil / ChrisTitus / OO ShutUp
  WinTitusConsumerFeatures: false,
  WinTitusHibernation: false,
  WinTitusPosh7Telemetry: false,
  WinTitusWPBT: false,
  WinTitusDiskCleanup: false,
  WinTitusServicesManual: false,
  WinTitusAdobeBlock: false,
  WinTitusRazerBlock: false,
  WinTitusBgApps: false,
  WinTitusFullscreenOpt: false,
  WinTitusNotifTray: false,
  WinTitusStorageSense: false,
  WinTitusTeredo: false,
  WinTitusEdgeDebloat: false,
  WinTitusIPv4Prefer: false,
  WinTitusEdgeRemove: false,
  WinTitusXboxComponents: false,
  WinTitusClassicMenu: false,
  WinTitusDisplayPerf: false,
  WinTitusShowExtensions: false,
  WinTitusShowHidden: false,
  OOShutupPrivacy: false,
  // Startup Apps
  su_discord: false,
  su_spotify: false,
  su_steam: false,
  su_onedrive: false,
  su_teams: false,
  su_skype: false,
  su_zoom: false,
  su_rtss: false,
  su_msiab: false,
  su_nvidia: false,
  su_ccleaner: false,
  su_realtek: false,
  su_logitech: false,
  su_corsair: false,
  su_amdradeon: false,
};

export const useOptimizationStore = create<OptimizationState>()(
  persist(
    (set) => ({
      tweaks: { ...DEFAULT_TWEAKS },
      nvidiaPreset: 'Balanced',
      systemRamGB: null,

      setSystemRamGB: (gb) => set({ systemRamGB: gb }),

      toggleTweak: (key) => set((state) => ({
        tweaks: { ...state.tweaks, [key]: !state.tweaks[key] }
      })),

      setTweak: (key, value) => set((state) => ({
        tweaks: { ...state.tweaks, [key]: value }
      })),

      setNvidiaPreset: (preset) => set({ nvidiaPreset: preset }),

      setAllTweaks: (tweaks) => set({ tweaks }),

      reset: () => set({ tweaks: { ...DEFAULT_TWEAKS }, nvidiaPreset: 'Balanced' }),
    }),
    {
      name: 'optigods-tweaks-v1',
      partialize: (state: OptimizationState) => ({ tweaks: state.tweaks, nvidiaPreset: state.nvidiaPreset }),
    }
  )
);
